/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;
import controlador.ComponentesControlador;
import controlador.ProveedorControlador;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import modelo.Componentes;
import modelo.Proveedor;
/**
 *
 * @author Grossling
 */
public class componentesForm2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form componentesForm2
     */
    public componentesForm2() {
        initComponents();
    }
    
    Componentes cmp = new Componentes();
    Proveedor prv = new Proveedor();
    
    ComponentesControlador cmpBD = new ComponentesControlador();
    ProveedorControlador prvBD = new ProveedorControlador();
    
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    DefaultComboBoxModel modelCombo = new DefaultComboBoxModel();
    
    int k;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNuevo = new org.edisoncor.gui.button.ButtonTask();
        bCancelar = new org.edisoncor.gui.button.ButtonTask();
        bGuardar = new org.edisoncor.gui.button.ButtonTask();
        bBorrar = new org.edisoncor.gui.button.ButtonTask();
        bBuscar = new org.edisoncor.gui.button.ButtonTask();
        jPanel2 = new javax.swing.JPanel();
        bPrimero = new org.edisoncor.gui.button.ButtonTask();
        bAnterior = new org.edisoncor.gui.button.ButtonTask();
        bSiguiente = new org.edisoncor.gui.button.ButtonTask();
        bUltimo = new org.edisoncor.gui.button.ButtonTask();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboProveedor = new javax.swing.JComboBox();
        jComboUnidad = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboIva = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Componentes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/componente.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N

        bNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430632277_document_add.png"))); // NOI18N
        bNuevo.setText("Nuevo");
        bNuevo.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bNuevo.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bNuevo.setDescription(" ");
        bNuevo.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bNuevo.setIconTextGap(2);
        bNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNuevoMouseClicked(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430630934_cross.png"))); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bCancelar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bCancelar.setDescription(" ");
        bCancelar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bCancelar.setIconTextGap(2);
        bCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarMouseClicked(evt);
            }
        });

        bGuardar.setForeground(new java.awt.Color(0, 51, 102));
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430629542_save_as-2-32.png"))); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bGuardar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bGuardar.setDescription(" ");
        bGuardar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bGuardar.setIconTextGap(2);
        bGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGuardarMouseClicked(evt);
            }
        });

        bBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430631493_trash.png"))); // NOI18N
        bBorrar.setText("Eliminar");
        bBorrar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bBorrar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bBorrar.setDescription(" ");
        bBorrar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bBorrar.setIconTextGap(2);
        bBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBorrarMouseClicked(evt);
            }
        });

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430631782_search_32.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bBuscar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bBuscar.setDescription(" ");
        bBuscar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bBuscar.setIconTextGap(2);
        bBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N

        bPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431297857_go-first-32.png"))); // NOI18N
        bPrimero.setText("Primero");
        bPrimero.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bPrimero.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bPrimero.setDescription(" ");
        bPrimero.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bPrimero.setIconTextGap(2);
        bPrimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPrimeroMouseClicked(evt);
            }
        });

        bAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431298335_go-previous-32.png"))); // NOI18N
        bAnterior.setText("Anterior");
        bAnterior.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bAnterior.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bAnterior.setDescription(" ");
        bAnterior.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bAnterior.setIconTextGap(2);
        bAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAnteriorMouseClicked(evt);
            }
        });

        bSiguiente.setForeground(new java.awt.Color(0, 51, 102));
        bSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431298287_go-next-32.png"))); // NOI18N
        bSiguiente.setText("Siguiente");
        bSiguiente.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bSiguiente.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bSiguiente.setDescription(" ");
        bSiguiente.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bSiguiente.setIconTextGap(2);
        bSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSiguienteMouseClicked(evt);
            }
        });

        bUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431297875_go-last-32.png"))); // NOI18N
        bUltimo.setText("Ultimo");
        bUltimo.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bUltimo.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bUltimo.setDescription(" ");
        bUltimo.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bUltimo.setIconTextGap(2);
        bUltimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bUltimoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 94, 137));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 94, 137));
        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPONENTES");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Componente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Aharoni", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setText("Código");

        txtCodigo.setName("txtcodigo"); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setName("txtdescripcion"); // NOI18N
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel4.setText("Unidad de medida");

        jLabel6.setText("Precio (Gs)");

        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel5.setText("Estado");

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INACTIVO", "ACTIVO" }));
        jComboEstado.setSelectedIndex(1);

        jLabel7.setText("Proveedor");

        jComboUnidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UNIDADES", "METROS", "KILOS", "LITROS", " " }));

        jLabel9.setText("Costo (Gs)");

        txtCosto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel10.setText("IVA");

        jComboIva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10%", "5%", "EXENTO" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboUnidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboIva, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28))
        );

        jPanel5.setBackground(new java.awt.Color(87, 123, 181));

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STOCK EN DEPOSITOS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (txtDescripcion.isEnabled() == true){
            return;
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("*".equals(txtCodigo.getText())) {
                
                BuscarForm bf = new BuscarForm(null, true);
                bf.columnas = "codigo, descripcion";
                bf.tabla = "Componentes";
                bf.order = "codigo_interno";
                bf.filtroBusqueda = "";
                bf.setLocationRelativeTo(this);
                bf.setVisible(true);
                
                for(int c=0; c<modelo.getRowCount(); c ++){
                    if (modelo.getValueAt(c, 0).toString().equals(bf.retorno)){
                        modoBusqueda(false);
                        establecerBotones("Edicion");
                        k = c;
                        datosActuales();
                    return;
                    }
                }
                
            }
            
            for(int c=0; c<modelo.getRowCount(); c ++){
                if (modelo.getValueAt(c, 0).toString().equals(txtCodigo.getText())){
                    modoBusqueda(false);
                    establecerBotones("Edicion");
                    k = c;
                    datosActuales();
                    return;
                }
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void bGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGuardarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bGuardar.isEnabled() == false){
            return;
        } else {
            guardar();
        }
    }//GEN-LAST:event_bGuardarMouseClicked

    private void bNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNuevoMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bNuevo.isEnabled() == false){
            return;
        } else {
            nuevo();
        }
    }//GEN-LAST:event_bNuevoMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        getComponentes();
        getProveedores();
        nuevo();
    }//GEN-LAST:event_formInternalFrameOpened

    private void bBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBorrarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bBorrar.isEnabled() == false){
            return;
        } else {
            borrar();
        }
    }//GEN-LAST:event_bBorrarMouseClicked

    private void bCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bCancelar.isEnabled() == false){
            return;
        } else {
            cancelar();
        }
    }//GEN-LAST:event_bCancelarMouseClicked

    private void bPrimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPrimeroMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bPrimero.isEnabled() == false){
            return;
        } else {
            primero();
        }
    }//GEN-LAST:event_bPrimeroMouseClicked

    private void bUltimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUltimoMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bUltimo.isEnabled() == false){
            return;
        } else {
            ultimo();
        }
    }//GEN-LAST:event_bUltimoMouseClicked

    private void bAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnteriorMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bAnterior.isEnabled() == false){
            return;
        } else {
            anterior();
        }
    }//GEN-LAST:event_bAnteriorMouseClicked

    private void bSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSiguienteMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bSiguiente.isEnabled() == false){
            return;
        } else {
            siguiente();
        }
    }//GEN-LAST:event_bSiguienteMouseClicked

    private void bBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bBuscar.isEnabled() == false){
            return;
        } else {
            buscar();
        }
    }//GEN-LAST:event_bBuscarMouseClicked

    private void primero(){
        if (modelo.getRowCount() == 0) {
            showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
            return;
        }    
            k = 0;
            datosActuales();
    }
    
    private void ultimo(){
         if (modelo.getRowCount() == 0) {
             showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
             return;
         }  
            k = modelo.getRowCount() - 1;
            datosActuales();
            
     }
    
    private void anterior(){
        if (modelo.getRowCount() == 0) {
             showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
             return;
         }      
            k = k - 1;
            if (k < 0) {
                showMessageDialog(null, "Has llegado al primer registro.", "Atención", INFORMATION_MESSAGE);
                k = k + 1;
                return;
            }
            datosActuales();
    }
    
    private void siguiente(){
        if (modelo.getRowCount() == 0) {
             showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
             return;
         }  
            k = k + 1;
            if (k == modelo.getRowCount()) {
                showMessageDialog(null, "Has llegado al ultimo registro.", "Atención", INFORMATION_MESSAGE);
                k = k - 1;
                return;
            }
            datosActuales();
    }
    
    private void datosActuales(){
            txtCodigo.setText(modelo.getValueAt(k, 0).toString());
            jComboUnidad.setSelectedIndex((int) modelo.getValueAt(k, 1));
            txtDescripcion.setText(modelo.getValueAt(k, 2).toString());
            jComboEstado.setSelectedIndex((int) modelo.getValueAt(k, 3));
            txtPrecio.setValue(modelo.getValueAt(k, 4));
            txtCosto.setValue(modelo.getValueAt(k, 7));
            jComboIva.setSelectedIndex((int) modelo.getValueAt(k, 8));
            getStock(txtCodigo.getText());
            try {
                jComboProveedor.setSelectedItem(prvBD.getDato((Integer)modelo.getValueAt(k, 6)));
            } catch (Exception ex) {
                showMessageDialog(null, "Combo proveedor no obtuvo datos", "Error", ERROR_MESSAGE); 
            }
    }
    
    private void buscar(){
        limpiar();
        establecerBotones("Buscar");
        modoBusqueda(true);
    }
    
    private void modoBusqueda(boolean v){
        if (v == true) {
        txtCodigo.requestFocusInWindow();
        txtCodigo.setBackground(Color.yellow);
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtCosto.setEnabled(false);
        jComboUnidad.setEnabled(false);
        jComboEstado.setEnabled(false);
        jComboIva.setEnabled(false);
        jComboProveedor.setEnabled(false);
        } else {
        txtCodigo.setBackground(Color.white);
        txtDescripcion.setEnabled(true);
        txtCosto.setEnabled(true);
        txtPrecio.setEnabled(true);
        jComboUnidad.setEnabled(true);
        jComboIva.setEnabled(true);
        jComboEstado.setEnabled(true);
        jComboProveedor.setEnabled(true);
        }
    }
    
    @SuppressWarnings("UnnecessaryReturnStatement")
    private void guardar(){
        if ("".equals(txtCodigo.getText())) {
            showMessageDialog(null, "Debe ingresar un código.", "Atención", INFORMATION_MESSAGE);
            txtCodigo.requestFocusInWindow();
            return;
        } else if ("".equals(txtDescripcion.getText())) {
            showMessageDialog(null, "Debe ingresar la descripción.", "Atención", INFORMATION_MESSAGE);
            txtDescripcion.requestFocusInWindow();
            return;
        } else if (("".equals(txtPrecio.getText())) || ("0".equals(txtPrecio.getText())) ) {
            showMessageDialog(null, "Debe ingresar el precio.", "Atención", INFORMATION_MESSAGE);
            txtPrecio.requestFocusInWindow();
            return;
        } else if (("".equals(txtCosto.getText())) || ("0".equals(txtCosto.getText())) ) {
            showMessageDialog(null, "Debe ingresar el precio.", "Atención", INFORMATION_MESSAGE);
            txtPrecio.requestFocusInWindow();
            return;
        } 
        else {
            cmp.setCodigo(txtCodigo.getText());
            cmp.setUnidad(jComboUnidad.getSelectedIndex());
            cmp.setDescripcion(txtDescripcion.getText());     
            cmp.setEstado(jComboEstado.getSelectedIndex()); 
            cmp.setCosto(Integer.parseInt(txtCosto.getValue().toString())); 
            cmp.setPrecio(Integer.parseInt(txtPrecio.getValue().toString()));
            cmp.setTipoIva(jComboIva.getSelectedIndex());
            
            try { 
                cmp.setIdProveedor(prvBD.getCodigo((String) jComboProveedor.getSelectedItem()));
            } catch (Exception ex) {
                showMessageDialog(null, "setIdProveedor " + ex, "Error", ERROR_MESSAGE);
            }
            
            if (bNuevo.isEnabled() == false) {
                try {
                    cmpBD.insert(cmp);
                    nuevo();
                    getComponentes();
                } catch (Exception ex) {
                    showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
                }
            } else {
                try {
                    cmp.setCodigoInterno((Integer) modelo.getValueAt(k, 5));
                    cmpBD.update(cmp);
                    getComponentes();
                    datosActuales();
                    getStock(txtCodigo.getText());
                } catch (Exception ex) {
                    showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
                }
            }
         }
    }
    
    private void borrar(){
        if(showConfirmDialog (null, "Está seguro de eliminar el componente seleccionado?", "Confirmar", YES_NO_OPTION) == YES_OPTION){
            try {
                if (cmpBD.tieneStock(txtCodigo.getText()) == true) {
                    showMessageDialog(null, "El artículo tiene Stock, no puede eliminarlo", "Atención", ERROR_MESSAGE); 
                    return;
                }
                cmpBD.delete(txtCodigo.getText());
                getComponentes();
                getStock(txtCodigo.getText());
                if (modelo.getRowCount() == 0) {establecerBotones("Vacio"); limpiar();}
                else{
                    if (k == 0) {datosActuales(); getStock(txtCodigo.getText());}
                    else{    
                    anterior(); getStock(txtCodigo.getText());}}
                
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        }
    }
    
    private void cancelar(){
        if(showConfirmDialog (null, "Está seguro de cancelar la operación?", "Confirmar", YES_NO_OPTION) == YES_OPTION){
            getComponentes();
            if (modelo.getRowCount() == 0) {
                limpiar(); 
                establecerBotones("Vacio"); 
                modoBusqueda(false); 
                return;
            }
            if (k >= 0){
                    limpiar(); 
                    datosActuales(); 
                    getStock(txtCodigo.getText()); 
                    establecerBotones("Edicion");
                    modoBusqueda(false);
                    return;
            }
        }
    }
    
    private void nuevo() {
        limpiar();
        establecerBotones("Nuevo");
        try {
            jComboEstado.setSelectedIndex(1);
            txtCodigo.requestFocusInWindow();
        } catch (Exception ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void limpiar() {
        txtCodigo.setText("");
        jComboUnidad.setSelectedIndex(0);
        jComboIva.setSelectedIndex(1);
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtCosto.setText("");
        jComboEstado.setSelectedIndex(1);
        jComboProveedor.setSelectedIndex(0);
        getStock("-1");
    }
    
    private void getComponentes() {
        try {
            try (ResultSet rs = cmpBD.datos()) {
                
                modelo.setRowCount(0);
                modelo.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs.getMetaData();
                
                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modelo.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void getProveedores() {
        try {
            try (ResultSet rs = prvBD.datoCombo()) {
                
                modelCombo.removeAllElements();
                
                while (rs.next()) {
                    modelCombo.addElement(rs.getObject("dato").toString());
                }
            jComboProveedor.setModel(modelCombo);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void getStock(String codigo) {
        try {
            try (ResultSet rs1 = cmpBD.datosStock(codigo)) {
                
                modelo2.setRowCount(0);
                modelo2.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs1.getMetaData();

                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modelo2.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs1.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs1.getObject(i+1);
                    }
                    modelo2.addRow(fila);
                }
                jTable1.setModel(modelo2);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void establecerBotones(String modo) {
        switch (modo) {
            case "Nuevo":
                bNuevo.setEnabled(false);
                bBorrar.setEnabled(false);
                bCancelar.setEnabled(true);
                bGuardar.setEnabled(true);
                bAnterior.setEnabled(false);
                bSiguiente.setEnabled(false);
                bPrimero.setEnabled(false);
                bUltimo.setEnabled(false);
                bBuscar.setEnabled(false);
                break;
            case "Edicion":
                bNuevo.setEnabled(true);
                bBorrar.setEnabled(true);
                bCancelar.setEnabled(false);
                bGuardar.setEnabled(true);
                bAnterior.setEnabled(true);
                bSiguiente.setEnabled(true);
                bPrimero.setEnabled(true);
                bUltimo.setEnabled(true);
                bBuscar.setEnabled(true);
                break;
            case "Vacio":
                bNuevo.setEnabled(true);
                bBorrar.setEnabled(false);
                bCancelar.setEnabled(false);
                bGuardar.setEnabled(false);
                bAnterior.setEnabled(false);
                bSiguiente.setEnabled(false);
                bPrimero.setEnabled(false);
                bUltimo.setEnabled(false);
                bBuscar.setEnabled(false);
                break;
            case "Buscar":
                bNuevo.setEnabled(false);
                bBorrar.setEnabled(false);
                bCancelar.setEnabled(true);
                bGuardar.setEnabled(false);
                bAnterior.setEnabled(false);
                bSiguiente.setEnabled(false);
                bPrimero.setEnabled(false);
                bUltimo.setEnabled(false);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask bAnterior;
    private org.edisoncor.gui.button.ButtonTask bBorrar;
    private org.edisoncor.gui.button.ButtonTask bBuscar;
    private org.edisoncor.gui.button.ButtonTask bCancelar;
    private org.edisoncor.gui.button.ButtonTask bGuardar;
    private org.edisoncor.gui.button.ButtonTask bNuevo;
    private org.edisoncor.gui.button.ButtonTask bPrimero;
    private org.edisoncor.gui.button.ButtonTask bSiguiente;
    private org.edisoncor.gui.button.ButtonTask bUltimo;
    private javax.swing.JComboBox jComboEstado;
    private javax.swing.JComboBox jComboIva;
    private javax.swing.JComboBox jComboProveedor;
    private javax.swing.JComboBox jComboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCosto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JFormattedTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
