/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;
import controlador.FacturaCabeceraCompraControlador;
import controlador.FacturaCabeceraVentaControlador;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import modelo.Venta;


/**
 *26/08/2015
 * @author anex
 */
public class DetallePagoVentaForm extends javax.swing.JInternalFrame {
  
    DefaultTableModel modeloPago = new DefaultTableModel();
    DefaultTableModel modeloNroFactura;
    FacturaCabeceraVentaControlador facturaCabeceraControlador = new FacturaCabeceraVentaControlador();
    Venta facturaVenta = new Venta();
    DecimalFormat formateador = new DecimalFormat("###,###.##");
    int total=0, i=0, pendiente=0, cambio=0, k2 = 0;
   
    
 public DetallePagoVentaForm() throws Exception {
        initComponents();
        getNroFactura();
        
        txtPagado.setEnabled(false);
        txtPendiente.setEnabled(false);
        txtCambio.setEnabled(false);
        jPanelCheque.setVisible(false);
        jPanelNotaCredito.setVisible(false);
        jPanelTarjeta.setVisible(false);
        
        modeloPago.addColumn("Forma de Pago");
        modeloPago.addColumn("Tarjeta nro.");
        modeloPago.addColumn("Autorizacion");
        modeloPago.addColumn("Total");
        modeloPago.isCellEditable(0,0);
        
        txtPendiente.setText("0");
        txtPagado.setText("0");
        txtCambio.setText("0");
        
    }
 

    private void getNroFactura() {
        
        modeloNroFactura=new DefaultTableModel();
        try {
            modeloNroFactura.setColumnCount(0);
            modeloNroFactura.setRowCount(0);
                      
            try (ResultSet rs = facturaCabeceraControlador.getNroFacturaDetalle()) {
           
                ResultSetMetaData rsMd = rs.getMetaData();
                
                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modeloNroFactura.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs.getObject(i+1);
                    }
                    modeloNroFactura.addRow(fila);
                }
            } catch (Exception ex) {
                showMessageDialog(null,  ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
   
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelVent = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bNuevo = new org.edisoncor.gui.button.ButtonTask();
        jBCancelar = new org.edisoncor.gui.button.ButtonTask();
        jBGuardar1 = new org.edisoncor.gui.button.ButtonTask();
        JCtipoPago = new javax.swing.JComboBox();
        lbTipoPago = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lbValor = new javax.swing.JLabel();
        txtNroFactura = new javax.swing.JTextField();
        lbNroFactura = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetallePago = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        }
        ;
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelCantidadTotal2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        txtPagado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPendiente = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detalle de Pago");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430364091_my-invoices.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        JpanelVent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 94, 137));
        jLabel7.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DETALLE DE PAGO");
        jLabel7.setOpaque(true);
        JpanelVent.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 990, 56));

        jPanel1.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 5));

        bNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadirPago.png"))); // NOI18N
        bNuevo.setText("Añadir");
        bNuevo.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bNuevo.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bNuevo.setDescription(" ");
        bNuevo.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bNuevo.setIconTextGap(2);
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(bNuevo);
        bNuevo.getAccessibleContext().setAccessibleName("Añadir ");

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        jBCancelar.setText("Eliminar Registro");
        jBCancelar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBCancelar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        jBCancelar.setDescription(" ");
        jBCancelar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        jBCancelar.setIconTextGap(2);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar);
        jBCancelar.getAccessibleContext().setAccessibleDescription("");

        jBGuardar1.setForeground(new java.awt.Color(0, 51, 102));
        jBGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jBGuardar1.setText("Guardar");
        jBGuardar1.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBGuardar1.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        jBGuardar1.setDescription(" ");
        jBGuardar1.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        jBGuardar1.setIconTextGap(2);
        jBGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar1);

        JpanelVent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 900, 55));

        JCtipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guaranies", "Tarjeta Debito", "Tarjeta Credito", "Cheque", "Nota de Credito" }));
        JCtipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCtipoPagoActionPerformed(evt);
            }
        });
        JpanelVent.add(JCtipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, 30));

        lbTipoPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbTipoPago.setText("Tipo de Pago");
        JpanelVent.add(lbTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));
        JpanelVent.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 140, -1));

        lbValor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbValor.setText("Valor:");
        lbValor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JpanelVent.add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        txtNroFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroFacturaKeyPressed(evt);
            }
        });
        JpanelVent.add(txtNroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, -1));

        lbNroFactura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbNroFactura.setText("Nº Factura");
        JpanelVent.add(lbNroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 10))); // NOI18N
        JpanelVent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 920, 140));
        JpanelVent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, -1));

        tbDetallePago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Forma Pago", "Tarjeta Nro.", "Autorizacion", "Total"
            }
        ));
        tbDetallePago.setEditingColumn(0);
        tbDetallePago.setFillsViewportHeight(true);
        tbDetallePago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbDetallePagoFocusLost(evt);
            }
        });
        tbDetallePago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbDetallePagoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbDetallePago);

        JpanelVent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 920, 230));

        jPanel3.setBackground(new java.awt.Color(51, 94, 137));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detalle de Pago");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JpanelVent.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 920, 30));
        JpanelVent.add(labelCantidadTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 200, -1));

        jLabel13.setText("Cambio");
        JpanelVent.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 60, -1));

        jLabel14.setText("Pagado");
        JpanelVent.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, -1));
        JpanelVent.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 90, -1));
        JpanelVent.add(txtPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 90, -1));

        jLabel15.setText("Pendiente");
        JpanelVent.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, -1, -1));
        JpanelVent.add(txtPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelVent, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelVent, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDetallePagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDetallePagoKeyPressed

     
    }//GEN-LAST:event_tbDetallePagoKeyPressed

    private void jBGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardar1ActionPerformed
        FacturaVentaForm.tbDetallePagoVenta.setModel(modeloPago);
    }//GEN-LAST:event_jBGuardar1ActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

       if(tbDetallePago.getSelectedRow() == -1){
            showMessageDialog(this, "Por favor seleccione una fila", "Atención", JOptionPane.WARNING_MESSAGE);
        }else{
            DecimalFormat formateadorDelet = new DecimalFormat("###,###.##");
            total=total-Integer.parseInt(tbDetallePago.getValueAt(tbDetallePago.getSelectedRow(), 3).toString().trim().replace(".", ""));
            String TotalFormat=formateadorDelet.format(total);
            txtPagado.setText(TotalFormat);
             
            if (Integer.parseInt(txtPagado.getText().trim().replace(".", ""))<Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim()) && pendiente!=0){
            pendiente=pendiente+Integer.parseInt(tbDetallePago.getValueAt(tbDetallePago.getSelectedRow(), 3).toString().trim().replace(".", ""));
            String PendienteFormat=formateadorDelet.format(pendiente);
            txtPendiente.setText(PendienteFormat);
            }else if (Integer.parseInt(txtPagado.getText().trim().replace(".", ""))==Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim())){
            pendiente=0;
            String PendienteFormat=formateadorDelet.format(pendiente);
            txtPendiente.setText(PendienteFormat);
            }else if (Integer.parseInt(txtPagado.getText().trim().replace(".", ""))<Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim()) && pendiente==0){
            pendiente=Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim())-Integer.parseInt(txtPagado.getText().trim().replace(".", ""));
            String PendienteFormat=formateadorDelet.format(pendiente);
            txtPendiente.setText(PendienteFormat);
            }
           
           
            
            if (Integer.parseInt(FacturaVentaForm.txtTotal.getText().trim().replace(".", ""))<=Integer.parseInt(txtPagado.getText().replace(".", "").trim())){
            cambio=Integer.parseInt(txtPagado.getText().replace(".", "").trim())-Integer.parseInt(FacturaVentaForm.txtTotal.getText().trim().replace(".", ""));
            String CambioFormat=formateadorDelet.format(cambio);
            txtCambio.setText(CambioFormat);
            }else{
            cambio=0; pendiente=0;
            String CambioFormat=formateadorDelet.format(cambio);
            txtCambio.setText(CambioFormat);
            }
            
            if (Integer.parseInt(txtPagado.getText().replace(".", "").trim())== 0 && Integer.parseInt(txtCambio.getText().replace(".", "").trim())==0){
            total=0; cambio=0;
            pendiente=Integer.parseInt(FacturaVentaForm.txtTotal.getText().trim().replace(".", ""));
            String PendienteFormat=formateadorDelet.format(pendiente);
            txtPendiente.setText(PendienteFormat);
            }
            

            i--;
            modeloPago.removeRow(tbDetallePago.getSelectedRow());                    
            tbDetallePago.setModel(modeloPago);
       }
           
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
       if (!"".equals(txtValor.getText())){
        if (JCtipoPago.getSelectedItem().toString().equals("Tarjeta Debito")  || JCtipoPago.getSelectedItem().toString().equals("Tarjeta Credito")){
            formateador = new DecimalFormat("###,###.##");
            
            String datos [] = new String [7];
            datos[0]=JCtipoPago.getSelectedItem().toString();
            datos[1]=txtNroTarjeta.getText();
            datos[2]=txtAutorizacionTarjeta.getText();
            datos[3]=formateador.format(Integer.parseInt(txtValor.getText()));
            datos[4]="";
            datos[5]="";
            datos[6]="";
            modeloPago.addRow(datos);  
        }
        if (JCtipoPago.getSelectedItem().toString().equals("Guaranies")){
            String datos [] = new String [7];
            datos[0]=JCtipoPago.getSelectedItem().toString();
            datos[1]="";
            datos[2]="";
            datos[3]=formateador.format(Integer.parseInt(txtValor.getText()));
            datos[4]="";
            datos[5]="";
            datos[6]="";
            modeloPago.addRow(datos);   
        }
        if (JCtipoPago.getSelectedItem().toString().equals("Cheque")){
            String datos [] = new String [7];
            datos[0]=JCtipoPago.getSelectedItem().toString();
            datos[1]=txtNroCheque.getText();
            datos[2]=txtAutorizacionCheque.getText();
            datos[3]=formateador.format(Integer.parseInt(txtValor.getText()));
            datos[4]="";
            datos[5]="";
            datos[6]="";
            modeloPago.addRow(datos);   
        }
        if (JCtipoPago.getSelectedItem().toString().equals("Nota de Credito")){
            String datos [] = new String [7];
            datos[0]=JCtipoPago.getSelectedItem().toString();
            datos[1]="";
            datos[2]="";
            datos[3]=formateador.format(Integer.parseInt(txtValor.getText()));
            datos[4]=txtValorDelCredito.getText();
            datos[5]=txtPendienteAplicar.getText();
            datos[6]="";
            modeloPago.addRow(datos);   
        }
        tbDetallePago.setModel(modeloPago);
        txtValor.setText("");
        txtNroTarjeta.setText("");
        txtAutorizacionTarjeta.setText("");
        
        
        total=total+Integer.parseInt(tbDetallePago.getValueAt(i, 3).toString().replace(".", "").trim());
        i++;
        String TotalFormat=formateador.format(total);
        txtPagado.setText(TotalFormat);
        
        pendiente=Integer.parseInt(txtPendiente.getText().replace(".", "").trim());
        
        if (Integer.parseInt(txtPagado.getText().replace(".", "").trim())==0){
        pendiente=Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim());
        }
        if (total< Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim())){
        pendiente=Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim())- total;
        String PendienteFormat=formateador.format(pendiente);
        txtPendiente.setText(PendienteFormat);
        }else{
        cambio=total-Integer.parseInt(FacturaVentaForm.txtTotal.getText().replace(".", "").trim());
        String cambioFormat=formateador.format(cambio);
        txtCambio.setText(cambioFormat);
        
        pendiente=0;
        String PendienteFormat=formateador.format(pendiente);
        txtPendiente.setText(PendienteFormat);

        }
       }else{
        showMessageDialog(this, "Debe ingresar un valor para añadir el pago", "Atención", JOptionPane.WARNING_MESSAGE);
       }
        
    }//GEN-LAST:event_bNuevoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    private void tbDetallePagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbDetallePagoFocusLost
 
    }//GEN-LAST:event_tbDetallePagoFocusLost

    private void JCtipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCtipoPagoActionPerformed

        if (JCtipoPago.getSelectedItem().toString().equals("Tarjeta Debito") || JCtipoPago.getSelectedItem().toString().equals("Tarjeta Credito")){
             jPanelCheque.setVisible(false);
             jPanelNotaCredito.setVisible(false);
             jPanelTarjeta.setVisible(true);
        }else if (JCtipoPago.getSelectedItem().toString().equals("Cheque")){ 
            jPanelTarjeta.setVisible(false);
            jPanelNotaCredito.setVisible(false);
            jPanelCheque.setVisible(true);
        }else if (JCtipoPago.getSelectedItem().toString().equals("Nota de Credito")){ 
            jPanelTarjeta.setVisible(false);
            jPanelNotaCredito.setVisible(true);
            jPanelCheque.setVisible(false);
        }else if (JCtipoPago.getSelectedItem().toString().equals("Guaranies")){ 
            jPanelTarjeta.setVisible(false);
            jPanelNotaCredito.setVisible(false);
            jPanelCheque.setVisible(false);
        }
    }//GEN-LAST:event_JCtipoPagoActionPerformed

    private void txtNroFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroFacturaKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("*".equals(txtNroFactura.getText())) {
                //TBdetalleCuenta2.setRowSelectionInterval(0,0);
                BuscarForm bf = new BuscarForm( null, true);
                bf.columnas = "v.nro_factura, v.precio_total";
                bf.tabla = "venta v";
                bf.order = "v.nro_factura";
                bf.filtroBusqueda = "es_factura = 'S' and estado != 'BORRADOR'"; 
                bf.setLocationRelativeTo(this);
                bf.setVisible(true);
                

                for(int c=0; c<modeloNroFactura.getRowCount(); c ++){
                    System.out.println("modelo row count "+modeloNroFactura.getRowCount());
                    if (modeloNroFactura.getValueAt(c, 1).toString().equals(bf.retorno)){
                        //System.out.println("MODELO "+modeloNroFactura.getValueAt(c, 1).toString());
                        k2 = c;
                        datosActualesNroFactura();
                    return;
                    }
                }
                
            getNroFactura();
            
            System.out.println(modeloNroFactura.getRowCount());
            for(int c=0; c<modeloNroFactura.getRowCount(); c ++){
                if (modeloNroFactura.getValueAt(c, 1).toString().equals(txtNroFactura.getText())){
                    k2 = c;                   
                    datosActualesNroFactura();
                   return;
                }
            }
        }
      }
    }//GEN-LAST:event_txtNroFacturaKeyPressed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCtipoPago;
    private javax.swing.JPanel JpanelVent;
    private org.edisoncor.gui.button.ButtonTask bNuevo;
    private org.edisoncor.gui.button.ButtonTask jBCancelar;
    private org.edisoncor.gui.button.ButtonTask jBGuardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidadTotal2;
    private javax.swing.JLabel lbNroFactura;
    private javax.swing.JLabel lbTipoPago;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTable tbDetallePago;
    public static javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtNroFactura;
    public static javax.swing.JTextField txtPagado;
    public static javax.swing.JTextField txtPendiente;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void datosActualesNroFactura() {
        DecimalFormat forma = new DecimalFormat("###,###.##"); 
        String nroFactura =forma.format(Integer.parseInt(modeloNroFactura.getValueAt(k2, 1).toString().trim().replace(".", "")));
        txtNroFactura.setText(nroFactura);
        String montoPendiente = forma.format(Integer.parseInt(modeloNroFactura.getValueAt(k2, 8).toString().trim().replace(".", "")));
        txtPendiente.setText(montoPendiente);
    }
}
