/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.permisos;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Pathy
 */
public class MenuPrincipalForm extends javax.swing.JFrame {
    String nombreUsuario;
    int codRol;
    String rolUsuario;
    private Dimension dim;
    

    /**
     * Creates new form MenuPrincipalForm
     */
    public MenuPrincipalForm() {
        initComponents();
        jDesktopPane1.setBorder(new Escritorio());
        this.setExtendedState(MAXIMIZED_BOTH);

       
    }
    permisos p = new permisos();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jXMonthView1 = new org.jdesktop.swingx.JXMonthView();
        lbUsuario = new javax.swing.JLabel();
        lbRol = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mProyecto = new javax.swing.JMenu();
        mComponente = new javax.swing.JMenuItem();
        mDeposito = new javax.swing.JMenuItem();
        mEntrada = new javax.swing.JMenuItem();
        mSalida = new javax.swing.JMenuItem();
        mTransferencia = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mCompra = new javax.swing.JMenu();
        mProveedor = new javax.swing.JMenuItem();
        mFacturaCompra = new javax.swing.JMenuItem();
        mNotaCreditoCompra = new javax.swing.JMenuItem();
        ReciboPagoProv = new javax.swing.JMenuItem();
        mVenta = new javax.swing.JMenu();
        mCliente = new javax.swing.JMenuItem();
        mPrefijo = new javax.swing.JMenuItem();
        mFacturaVenta = new javax.swing.JMenuItem();
        mNotaCreditoVenta = new javax.swing.JMenuItem();
        mReciboPago = new javax.swing.JMenuItem();
        mAdministracion = new javax.swing.JMenu();
        mRol = new javax.swing.JMenuItem();
        mVentana = new javax.swing.JMenuItem();
        mPermiso = new javax.swing.JMenuItem();
        mUsuario = new javax.swing.JMenuItem();
        mConsultar = new javax.swing.JMenu();
        mConsultarFacturaVenta = new javax.swing.JMenuItem();
        mConsultarFacturaCompra = new javax.swing.JMenuItem();
        mConsultarNotaCreditoCompra = new javax.swing.JMenuItem();
        mConsultarNotaCreditoVenta = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        consultarMovimientoVenta = new javax.swing.JMenuItem();
        consultarMovimientoCompra = new javax.swing.JMenuItem();
        HechaukaCompra = new javax.swing.JMenuItem();
        HechaukaVenta = new javax.swing.JMenuItem();
        ExtractoCliente = new javax.swing.JMenuItem();
        ExtractoProveedor = new javax.swing.JMenuItem();
        LibroCompras = new javax.swing.JMenuItem();
        LibroCompras1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mAnularFacturaVenta = new javax.swing.JMenuItem();
        mAnularFacturaCompra = new javax.swing.JMenuItem();
        mAnularNotaCreditoCompra = new javax.swing.JMenuItem();
        mAnularNotaCreditoVenta = new javax.swing.JMenuItem();
        mAnularPagoProveedor = new javax.swing.JMenuItem();
        mAnularPagoCliente = new javax.swing.JMenuItem();
        mAcercaDe = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INTERSAT MANAGEMENT TOOL");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/log.jpg")).getImage());
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane2.setForeground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setAutoscrolls(true);

        clockFace1.setBackground(new java.awt.Color(0, 255, 204));
        clockFace1.setRomano(false);

        jXMonthView1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXMonthView1.setFlaggedDayForeground(new java.awt.Color(0, 204, 204));
        jXMonthView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXMonthView1ActionPerformed(evt);
            }
        });

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(0, 102, 153));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRol.setForeground(new java.awt.Color(0, 153, 204));
        lbRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1650, 1650, 1650)
                        .addComponent(jXMonthView1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1650, 1650, 1650)
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1680, 1680, 1680)
                        .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1650, 1650, 1650)
                        .addComponent(lbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1610, 1610, 1610)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(680, 680, 680)
                        .addComponent(jXMonthView1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(clockFace1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jXMonthView1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbRol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane2.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/project.png"))); // NOI18N
        mProyecto.setText("Proyecto");

        mComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/componente.png"))); // NOI18N
        mComponente.setText("Componentes");
        mComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mComponenteActionPerformed(evt);
            }
        });
        mProyecto.add(mComponente);

        mDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deposito.png"))); // NOI18N
        mDeposito.setText("Depositos");
        mDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDepositoActionPerformed(evt);
            }
        });
        mProyecto.add(mDeposito);

        mEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrada.png"))); // NOI18N
        mEntrada.setText("Entradas");
        mEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEntradaActionPerformed(evt);
            }
        });
        mProyecto.add(mEntrada);

        mSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        mSalida.setText("Salidas");
        mSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalidaActionPerformed(evt);
            }
        });
        mProyecto.add(mSalida);

        mTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/transferencia.png"))); // NOI18N
        mTransferencia.setText("Transferencias");
        mTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTransferenciaActionPerformed(evt);
            }
        });
        mProyecto.add(mTransferencia);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431302134_toolbox.png"))); // NOI18N
        jMenuItem1.setText("Proyecto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mProyecto.add(jMenuItem1);

        jMenuBar1.add(mProyecto);

        mCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compra.png"))); // NOI18N
        mCompra.setText("Compra");

        mProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        mProveedor.setText("Proveedor");
        mProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProveedorActionPerformed(evt);
            }
        });
        mCompra.add(mProveedor);

        mFacturaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturaCompra.png"))); // NOI18N
        mFacturaCompra.setText("Factura Compra");
        mFacturaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFacturaCompraActionPerformed(evt);
            }
        });
        mCompra.add(mFacturaCompra);

        mNotaCreditoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1434930447_data-edit.png"))); // NOI18N
        mNotaCreditoCompra.setText("Nota Crédito Compra");
        mNotaCreditoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNotaCreditoCompraActionPerformed(evt);
            }
        });
        mCompra.add(mNotaCreditoCompra);

        ReciboPagoProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reciboCompra.png"))); // NOI18N
        ReciboPagoProv.setText("Recibo de Pago");
        ReciboPagoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciboPagoProvActionPerformed(evt);
            }
        });
        mCompra.add(ReciboPagoProv);

        jMenuBar1.add(mCompra);

        mVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta.png"))); // NOI18N
        mVenta.setText("Venta");
        mVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentaActionPerformed(evt);
            }
        });

        mCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        mCliente.setText("Cliente");
        mCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClienteActionPerformed(evt);
            }
        });
        mVenta.add(mCliente);

        mPrefijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prefijo.png"))); // NOI18N
        mPrefijo.setText("Prefijo Factura");
        mPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPrefijoActionPerformed(evt);
            }
        });
        mVenta.add(mPrefijo);

        mFacturaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura_venta.png"))); // NOI18N
        mFacturaVenta.setText("Factura Venta");
        mFacturaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFacturaVentaActionPerformed(evt);
            }
        });
        mVenta.add(mFacturaVenta);

        mNotaCreditoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notaCredito.png"))); // NOI18N
        mNotaCreditoVenta.setText("Nota Crédito Venta");
        mNotaCreditoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNotaCreditoVentaActionPerformed(evt);
            }
        });
        mVenta.add(mNotaCreditoVenta);

        mReciboPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reciboVenta.png"))); // NOI18N
        mReciboPago.setText("Recibo de Pago");
        mReciboPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReciboPagoActionPerformed(evt);
            }
        });
        mVenta.add(mReciboPago);

        jMenuBar1.add(mVenta);

        mAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administracion.png"))); // NOI18N
        mAdministracion.setText("Administración");

        mRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rol.png"))); // NOI18N
        mRol.setText("Roles");
        mRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRolActionPerformed(evt);
            }
        });
        mAdministracion.add(mRol);

        mVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventana.png"))); // NOI18N
        mVentana.setText("Ventanas");
        mVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentanaActionPerformed(evt);
            }
        });
        mAdministracion.add(mVentana);

        mPermiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/permisos.png"))); // NOI18N
        mPermiso.setText("Roles y Ventanas");
        mPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPermisoActionPerformed(evt);
            }
        });
        mAdministracion.add(mPermiso);

        mUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        mUsuario.setText("Usuario");
        mUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsuarioActionPerformed(evt);
            }
        });
        mAdministracion.add(mUsuario);

        jMenuBar1.add(mAdministracion);

        mConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuConsultar.png"))); // NOI18N
        mConsultar.setText("Consultar");

        mConsultarFacturaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarFacturaVenta.png"))); // NOI18N
        mConsultarFacturaVenta.setText("Consultar Factura Venta");
        mConsultarFacturaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultarFacturaVentaActionPerformed(evt);
            }
        });
        mConsultar.add(mConsultarFacturaVenta);

        mConsultarFacturaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarFacturaCompra.png"))); // NOI18N
        mConsultarFacturaCompra.setText("Consultar Factura Compra");
        mConsultarFacturaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultarFacturaCompraActionPerformed(evt);
            }
        });
        mConsultar.add(mConsultarFacturaCompra);

        mConsultarNotaCreditoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarNotaCreditoCompra.png"))); // NOI18N
        mConsultarNotaCreditoCompra.setText("Consultar Nota de Crédito - Compra");
        mConsultarNotaCreditoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultarNotaCreditoCompraActionPerformed(evt);
            }
        });
        mConsultar.add(mConsultarNotaCreditoCompra);

        mConsultarNotaCreditoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarNotaCreditoVenta.png"))); // NOI18N
        mConsultarNotaCreditoVenta.setText("Consultar Nota de Crédito - Venta");
        mConsultarNotaCreditoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultarNotaCreditoVentaActionPerformed(evt);
            }
        });
        mConsultar.add(mConsultarNotaCreditoVenta);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarStock.png"))); // NOI18N
        jMenuItem2.setText("Consultar Stock");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mConsultar.add(jMenuItem2);

        consultarMovimientoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaCuentaCliente.png"))); // NOI18N
        consultarMovimientoVenta.setText("Consultar Movimiento Venta");
        consultarMovimientoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMovimientoVentaActionPerformed(evt);
            }
        });
        mConsultar.add(consultarMovimientoVenta);

        consultarMovimientoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarCuentaProveedor.png"))); // NOI18N
        consultarMovimientoCompra.setText("Consultar Movimiento Compra");
        consultarMovimientoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMovimientoCompraActionPerformed(evt);
            }
        });
        mConsultar.add(consultarMovimientoCompra);

        HechaukaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hechauka.png"))); // NOI18N
        HechaukaCompra.setText("Hechauka Compra");
        HechaukaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HechaukaCompraActionPerformed(evt);
            }
        });
        mConsultar.add(HechaukaCompra);

        HechaukaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hechauka2.png"))); // NOI18N
        HechaukaVenta.setText("Hechauka Venta");
        HechaukaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HechaukaVentaActionPerformed(evt);
            }
        });
        mConsultar.add(HechaukaVenta);

        ExtractoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuentaCliente.png"))); // NOI18N
        ExtractoCliente.setText("Extracto Cliente");
        ExtractoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtractoClienteActionPerformed(evt);
            }
        });
        mConsultar.add(ExtractoCliente);

        ExtractoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuentasProveedores.png"))); // NOI18N
        ExtractoProveedor.setText("Extracto Proveedor");
        ExtractoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtractoProveedorActionPerformed(evt);
            }
        });
        mConsultar.add(ExtractoProveedor);

        LibroCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libroCompra.png"))); // NOI18N
        LibroCompras.setText("Libro Compras");
        LibroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroComprasActionPerformed(evt);
            }
        });
        mConsultar.add(LibroCompras);

        LibroCompras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libroVenta.png"))); // NOI18N
        LibroCompras1.setText("Libro Ventas");
        LibroCompras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroCompras1ActionPerformed(evt);
            }
        });
        mConsultar.add(LibroCompras1);

        jMenuBar1.add(mConsultar);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anulaciones.png"))); // NOI18N
        jMenu1.setText("Anulaciones");

        mAnularFacturaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anular_factura2.png"))); // NOI18N
        mAnularFacturaVenta.setText("Anular Factura Venta");
        mAnularFacturaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnularFacturaVentaActionPerformed(evt);
            }
        });
        jMenu1.add(mAnularFacturaVenta);

        mAnularFacturaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anularFacturaCompra.png"))); // NOI18N
        mAnularFacturaCompra.setText("Anular Factura Compra");
        mAnularFacturaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnularFacturaCompraActionPerformed(evt);
            }
        });
        jMenu1.add(mAnularFacturaCompra);

        mAnularNotaCreditoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anularNotaCreditoCompra.png"))); // NOI18N
        mAnularNotaCreditoCompra.setText("Anular Nota de Crédito - Compra");
        mAnularNotaCreditoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnularNotaCreditoCompraActionPerformed(evt);
            }
        });
        jMenu1.add(mAnularNotaCreditoCompra);

        mAnularNotaCreditoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anularNotaCreditoVenta.png"))); // NOI18N
        mAnularNotaCreditoVenta.setText("Anular Nota de Crédito - Venta");
        mAnularNotaCreditoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnularNotaCreditoVentaActionPerformed(evt);
            }
        });
        jMenu1.add(mAnularNotaCreditoVenta);

        mAnularPagoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagoProvanular.png"))); // NOI18N
        mAnularPagoProveedor.setText("Anular Pago Proveedor");
        mAnularPagoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnularPagoProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(mAnularPagoProveedor);

        mAnularPagoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anularPagoCli.png"))); // NOI18N
        mAnularPagoCliente.setText("Anular Pago Cliente");
        mAnularPagoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnularPagoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mAnularPagoCliente);

        jMenuBar1.add(jMenu1);

        mAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acercaDe.png"))); // NOI18N
        mAcercaDe.setText("Acerca de");
        mAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mAcercaDeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mAcercaDe);

        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        mSalir.setText("Salir");
        mSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mSalirMenuSelected(evt);
            }
        });
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentaActionPerformed
       
       
    }//GEN-LAST:event_mVentaActionPerformed

    private void mClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClienteActionPerformed
       ClienteForm prueba = new ClienteForm();
       try {
            if (p.tiene(prueba.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(prueba);
       prueba.show();
    }//GEN-LAST:event_mClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbUsuario.setText("Bienvenido "+nombreUsuario);
        lbRol.setText("Rol "+rolUsuario);
    }//GEN-LAST:event_formWindowOpened

    private void mComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mComponenteActionPerformed
       componentesForm2 cf2 = new componentesForm2();
       try {
            if (p.tiene(cf2.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(cf2);
       cf2.show();
    }//GEN-LAST:event_mComponenteActionPerformed

    private void mDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDepositoActionPerformed
       depositosForm2 dp2 = new depositosForm2();
       try {
            if (p.tiene(dp2.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(dp2);
       dp2.show();
    }//GEN-LAST:event_mDepositoActionPerformed

    private void mEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEntradaActionPerformed
      entradaForm2 ef2 = new entradaForm2();
       try {
            if (p.tiene(ef2.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(ef2);
       ef2.show();
    }//GEN-LAST:event_mEntradaActionPerformed

    private void mSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalidaActionPerformed
       salidaForm2 sf2 = new salidaForm2();
       try {
            if (p.tiene(sf2.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(sf2);
       sf2.show();
    }//GEN-LAST:event_mSalidaActionPerformed

    private void mTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTransferenciaActionPerformed
       transferenciaForm2 tf2 = new transferenciaForm2();
       try {
            if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(tf2);
       tf2.show();
    }//GEN-LAST:event_mTransferenciaActionPerformed

    private void mProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProveedorActionPerformed
       ProveedorInternalForm tf2 = new ProveedorInternalForm();
       try {
            if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.jDesktopPane1.add(tf2);
       tf2.show();
       tf2.setSize(1500, 600);
    }//GEN-LAST:event_mProveedorActionPerformed

    private void mFacturaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFacturaCompraActionPerformed
        try {
            FacturaCompraForm tf2 = new FacturaCompraForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mFacturaCompraActionPerformed

    private void mUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsuarioActionPerformed
      try {
            UsuarioForm tf2 = new UsuarioForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0 ){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(p.codJefe() != this.codRol){
                    showMessageDialog(this, "Solo el jefe tiene acceso a esta ventana", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mUsuarioActionPerformed

    private void mRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRolActionPerformed
        try {
            RolForm tf2 = new RolForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0 ){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(p.codJefe() != this.codRol){
                    showMessageDialog(this, "Solo el jefe tiene acceso a esta ventana", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mRolActionPerformed

    private void mVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentanaActionPerformed
       try {
            VentanaInternalForm tf2 = new VentanaInternalForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0 ){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(p.codJefe() != this.codRol){
                    showMessageDialog(this, "Solo el jefe tiene acceso a esta ventana", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mVentanaActionPerformed

    private void mPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPermisoActionPerformed
       try {
            VentanaRolInternalForm tf2 = new VentanaRolInternalForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0 ){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(p.codJefe() != this.codRol){
                    showMessageDialog(this, "Solo el jefe tiene acceso a esta ventana", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mPermisoActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
       LoginForm login = new LoginForm();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_mSalirActionPerformed

    private void mAnularFacturaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnularFacturaVentaActionPerformed
       try {
            AnularFacturaVentaForm tf2 = new AnularFacturaVentaForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                   showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                   return;
               }
            } catch (Exception ex) {
               Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mAnularFacturaVentaActionPerformed

    private void mFacturaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFacturaVentaActionPerformed
         try {
            FacturaVentaForm tf2 = new FacturaVentaForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mFacturaVentaActionPerformed

    private void mPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPrefijoActionPerformed
      try {
            PrefijoFacturaInternalForm tf2 = new PrefijoFacturaInternalForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mPrefijoActionPerformed

    private void mConsultarFacturaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultarFacturaVentaActionPerformed
      try {
            ConsultarFacturaVentaForm tf2 = new ConsultarFacturaVentaForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mConsultarFacturaVentaActionPerformed

    private void mConsultarFacturaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultarFacturaCompraActionPerformed
       try {
            ConsultarFacturaCompraForm tf2 = new ConsultarFacturaCompraForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mConsultarFacturaCompraActionPerformed

    private void mAnularFacturaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnularFacturaCompraActionPerformed
         try {
            AnularFacturaCompraForm tf2 = new AnularFacturaCompraForm();
            try {
               if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mAnularFacturaCompraActionPerformed

    private void mConsultarNotaCreditoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultarNotaCreditoVentaActionPerformed
         try {
            ConsultarNotaCreditoVentaForm tf2 = new ConsultarNotaCreditoVentaForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mConsultarNotaCreditoVentaActionPerformed

    private void mConsultarNotaCreditoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultarNotaCreditoCompraActionPerformed
        try {
            ConsultarNotaCreditoCompraForm tf2 = new ConsultarNotaCreditoCompraForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mConsultarNotaCreditoCompraActionPerformed

    private void mAnularNotaCreditoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnularNotaCreditoVentaActionPerformed
        try {
            AnularNotaCreditoVenta tf2 = new AnularNotaCreditoVenta();
           try {
               if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
               }
           } catch (Exception ex) {
               Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
           tf2.show();
       } catch (Exception ex) {
           Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_mAnularNotaCreditoVentaActionPerformed

    private void mAnularNotaCreditoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnularNotaCreditoCompraActionPerformed
        try {
            AnularNotaCreditoCompra tf2 = new AnularNotaCreditoCompra();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                   showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_mAnularNotaCreditoCompraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            ProyectosForm2 tf2 = new ProyectosForm2();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mAnularPagoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnularPagoProveedorActionPerformed
       try {
            AnularPagoProveedorForm tf2 = new AnularPagoProveedorForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mAnularPagoProveedorActionPerformed

    private void mAnularPagoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnularPagoClienteActionPerformed
       try {
           AnularPagoClienteForm tf2 = new AnularPagoClienteForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                   showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
      } catch (Exception ex) {
         Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_mAnularPagoClienteActionPerformed

    private void mNotaCreditoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNotaCreditoCompraActionPerformed
       try {
            NotaCreditoCompraForm tf2 = new NotaCreditoCompraForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mNotaCreditoCompraActionPerformed

    private void mNotaCreditoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNotaCreditoVentaActionPerformed
         try {
             NotaCreditoVentaForm tf2 = new NotaCreditoVentaForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mNotaCreditoVentaActionPerformed

    private void mReciboPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReciboPagoActionPerformed
        try {
             ReciboClienteForm tf2 = new ReciboClienteForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mReciboPagoActionPerformed

    private void ReciboPagoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReciboPagoProvActionPerformed
        try {
             ReciboProveedorForm tf2 = new ReciboProveedorForm();
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReciboPagoProvActionPerformed

    private void mSalirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mSalirMenuSelected
        LoginForm login = new LoginForm();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_mSalirMenuSelected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ConsultarStockForm consultarStock = new ConsultarStockForm();
        this.jDesktopPane1.add(consultarStock);
        consultarStock.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void consultarMovimientoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMovimientoVentaActionPerformed
        try {
            MovimientoVentaForm tf2 = new MovimientoVentaForm();
            tf2.setSize(600, 300);  
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarMovimientoVentaActionPerformed

    private void consultarMovimientoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMovimientoCompraActionPerformed
        try {
            MovimientoCompraForm tf2 = new MovimientoCompraForm();
            tf2.setSize(600, 300);  
            try {
                if (p.tiene(tf2.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf2);
            tf2.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarMovimientoCompraActionPerformed

    private void mAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAcercaDeMouseClicked
         try { 
            Runtime run = Runtime.getRuntime();
            String path = new String(" C:\\Users\\Any\\Documents\\NetBeansProjects\\helpIntersat.chm"); 
            Process pro = run.exec("hh.exe" + path);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mAcercaDeMouseClicked

    private void HechaukaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HechaukaCompraActionPerformed
            try {
            HechaukaCompraForm tf4 = new HechaukaCompraForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                       

    private void mConsultarFacturaVenta2ActionPerformed(java.awt.event.ActionEvent evt) {                                                        
         try {
            HechaukaVentaForm tf4 = new HechaukaVentaForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_HechaukaCompraActionPerformed

    private void HechaukaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HechaukaVentaActionPerformed
          try {
            HechaukaVentaForm tf4 = new HechaukaVentaForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HechaukaVentaActionPerformed

    private void ExtractoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtractoClienteActionPerformed
        try {
            ExtractoCuentaClienteForm tf4 = new ExtractoCuentaClienteForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExtractoClienteActionPerformed

    private void ExtractoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtractoProveedorActionPerformed
       try {
            ExtractoCuentaProveedorForm tf4 = new ExtractoCuentaProveedorForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExtractoProveedorActionPerformed

    private void LibroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroComprasActionPerformed
        try {
            LibroCompraForm tf4 = new LibroCompraForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LibroComprasActionPerformed

    private void LibroCompras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroCompras1ActionPerformed
          try {
            LibroVentaForm tf4 = new LibroVentaForm();
            tf4.setSize(600, 300);
            try {
                if (p.tiene(tf4.getTitle(),this.codRol) == 0){
                    showMessageDialog(this, "Sin permiso", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(tf4);
            tf4.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LibroCompras1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jXMonthView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXMonthView1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXMonthView1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExtractoCliente;
    private javax.swing.JMenuItem ExtractoProveedor;
    private javax.swing.JMenuItem HechaukaCompra;
    private javax.swing.JMenuItem HechaukaVenta;
    private javax.swing.JMenuItem LibroCompras;
    private javax.swing.JMenuItem LibroCompras1;
    private javax.swing.JMenuItem ReciboPagoProv;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JMenuItem consultarMovimientoCompra;
    private javax.swing.JMenuItem consultarMovimientoVenta;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXMonthView jXMonthView1;
    private javax.swing.JLabel lbRol;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenu mAcercaDe;
    private javax.swing.JMenu mAdministracion;
    private javax.swing.JMenuItem mAnularFacturaCompra;
    private javax.swing.JMenuItem mAnularFacturaVenta;
    private javax.swing.JMenuItem mAnularNotaCreditoCompra;
    private javax.swing.JMenuItem mAnularNotaCreditoVenta;
    private javax.swing.JMenuItem mAnularPagoCliente;
    private javax.swing.JMenuItem mAnularPagoProveedor;
    private javax.swing.JMenuItem mCliente;
    private javax.swing.JMenuItem mComponente;
    private javax.swing.JMenu mCompra;
    private javax.swing.JMenu mConsultar;
    private javax.swing.JMenuItem mConsultarFacturaCompra;
    private javax.swing.JMenuItem mConsultarFacturaVenta;
    private javax.swing.JMenuItem mConsultarNotaCreditoCompra;
    private javax.swing.JMenuItem mConsultarNotaCreditoVenta;
    private javax.swing.JMenuItem mDeposito;
    private javax.swing.JMenuItem mEntrada;
    private javax.swing.JMenuItem mFacturaCompra;
    private javax.swing.JMenuItem mFacturaVenta;
    private javax.swing.JMenuItem mNotaCreditoCompra;
    private javax.swing.JMenuItem mNotaCreditoVenta;
    private javax.swing.JMenuItem mPermiso;
    private javax.swing.JMenuItem mPrefijo;
    private javax.swing.JMenuItem mProveedor;
    private javax.swing.JMenu mProyecto;
    private javax.swing.JMenuItem mReciboPago;
    private javax.swing.JMenuItem mRol;
    private javax.swing.JMenuItem mSalida;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem mTransferencia;
    private javax.swing.JMenuItem mUsuario;
    private javax.swing.JMenu mVenta;
    private javax.swing.JMenuItem mVentana;
    // End of variables declaration//GEN-END:variables
}
