

package vista;

import modelo.PrefijoFactura;
import controlador.PrefijoFacturaControlador;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Pathy
 */
public class PrefijoFacturaInternalForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrefijoFacturaInternalForm
     */
    public PrefijoFacturaInternalForm() {
        initComponents();
    }

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    PrefijoFactura prefijoFactura = new PrefijoFactura();
    PrefijoFacturaControlador prefijoBD = new PrefijoFacturaControlador();
    String nroFactura = "";
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGuardar = new org.edisoncor.gui.button.ButtonTask();
        bCancelar = new org.edisoncor.gui.button.ButtonTask();
        jPanel1 = new javax.swing.JPanel();
        txtNroInicialFactura = new javax.swing.JTextField();
        txtPrefijo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNroFinalFactura = new javax.swing.JTextField();
        lbTipoDocumento = new javax.swing.JLabel();
        comboTipoDocumento = new javax.swing.JComboBox();
        lbTimbrado = new javax.swing.JLabel();
        txtTimbrado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lote Factura");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prefijo.png"))); // NOI18N

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        bGuardar.setText(" ");
        bGuardar.setToolTipText("Guardar");
        bGuardar.setCategoryFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        bGuardar.setCategorySmallFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        bGuardar.setDescription(" ");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bCancelar.setText(" ");
        bCancelar.setToolTipText("Cancelar");
        bCancelar.setCategoryFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        bCancelar.setCategorySmallFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        bCancelar.setDescription(" ");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle de lote ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 10))); // NOI18N

        txtNroInicialFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroInicialFacturaActionPerformed(evt);
            }
        });
        txtNroInicialFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroInicialFacturaKeyTyped(evt);
            }
        });

        txtPrefijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrefijoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel1.setText("Número de inicio de prefijo");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel2.setText("Número inicial");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel3.setText("Número final");

        txtNroFinalFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroFinalFacturaKeyTyped(evt);
            }
        });

        lbTipoDocumento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbTipoDocumento.setText("Tipo de Documento");

        comboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "N" }));
        comboTipoDocumento.setSelectedIndex(-1);

        lbTimbrado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbTimbrado.setText("Timbrado Número");

        txtTimbrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimbradoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lbTipoDocumento)
                    .addComponent(lbTimbrado))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNroInicialFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txtPrefijo)
                    .addComponent(txtNroFinalFactura)
                    .addComponent(comboTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTimbrado))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNroInicialFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNroFinalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTimbrado)
                    .addComponent(txtTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoDocumento)
                    .addComponent(comboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 94, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(385, 47));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lotes de factura y nota de crédito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try {
            guardar();
        } catch (Exception ex) {
            Logger.getLogger(PrefijoFacturaInternalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void txtNroInicialFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroInicialFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroInicialFacturaActionPerformed

    private void txtPrefijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrefijoKeyTyped
        /* if (txtPrefijo.getText().length() > 2) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }*/
    }//GEN-LAST:event_txtPrefijoKeyTyped

    private void txtNroInicialFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroInicialFacturaKeyTyped
       if (txtNroInicialFactura.getText().length() > 6) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNroInicialFacturaKeyTyped

    private void txtNroFinalFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroFinalFacturaKeyTyped
        if (txtNroFinalFactura.getText().length() > 6) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNroFinalFacturaKeyTyped

    private void txtTimbradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimbradoKeyTyped
         if (txtTimbrado.getText().length() > 7) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTimbradoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask bCancelar;
    private org.edisoncor.gui.button.ButtonTask bGuardar;
    private javax.swing.JComboBox comboTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTimbrado;
    private javax.swing.JLabel lbTipoDocumento;
    private javax.swing.JTextField txtNroFinalFactura;
    private javax.swing.JTextField txtNroInicialFactura;
    private javax.swing.JTextField txtPrefijo;
    private javax.swing.JTextField txtTimbrado;
    // End of variables declaration//GEN-END:variables

    
    /*Guarda los datos ingresados luego de verificar que no haya campos vacíos */
    
    private void guardar() throws Exception {
               
            if (txtPrefijo.getText().trim().isEmpty() == true) {
                showMessageDialog(this, "Campo prefijo vacío, por favor ingrese un valor ", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (txtPrefijo.getText().trim().length() < 7) {
                showMessageDialog(this, "El prefijo debe tener siete dígitos ", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            if(txtNroInicialFactura.getText().trim().isEmpty() == true){
                showMessageDialog(this, "Campo número inicial vacío, por favor ingrese un valor ", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
             if(txtNroFinalFactura.getText().trim().isEmpty() == true){
                showMessageDialog(this, "Campo número final vacío, por favor ingrese un valor ", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
             
              if(txtTimbrado.getText().trim().isEmpty() == true){
                showMessageDialog(this, "Campo timbrado vacío, por favor ingrese un valor ", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (comboTipoDocumento.getSelectedIndex() == -1) {
                showMessageDialog(null, "Debe seleccionar el tipo de documento", "Atención", INFORMATION_MESSAGE);
                return;
            }   
            
            if(comboTipoDocumento.getSelectedItem().equals("F") && prefijoBD.existeNroInicialFactura(Integer.parseInt(txtNroInicialFactura.getText())) > 0){
                 showMessageDialog(null, "Ya existe este número inicial de factura", "Atención", INFORMATION_MESSAGE);
                return;
            }
            
            if(comboTipoDocumento.getSelectedItem().equals("F") && prefijoBD.existeNroFinalFactura(Integer.parseInt(txtNroFinalFactura.getText())) > 0){
                 showMessageDialog(null, "Ya existe este número final de factura", "Atención", INFORMATION_MESSAGE);
                return;
            }
            
             if(comboTipoDocumento.getSelectedItem().equals("N") && prefijoBD.existeNroInicialNotaCredito(Integer.parseInt(txtNroInicialFactura.getText())) > 0){
                 showMessageDialog(null, "Ya existe este número inicial de nota de crédito", "Atención", INFORMATION_MESSAGE);
                return;
            }
          
             if(comboTipoDocumento.getSelectedItem().equals("N") && prefijoBD.existeNroFinalNotaCredito(Integer.parseInt(txtNroFinalFactura.getText())) > 0){
                 showMessageDialog(null, "Ya existe este número final de nota de crédito", "Atención", INFORMATION_MESSAGE);
                return;
            } 
             
             if (showConfirmDialog(null, "Está seguro de guardar los datos?", "Confirmar", YES_NO_OPTION) == YES_OPTION) {
               if(txtNroFinalFactura.getText().trim().isEmpty() == true){
                showMessageDialog(this, "Campo número de factura final vacío, por favor ingrese un valor ", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
            prefijoFactura.setIdprefijo(prefijoBD.nuevoCodigo());
            prefijoFactura.setPrefijo(txtPrefijo.getText());
            prefijoFactura.setPrincipiofactura(Integer.parseInt(txtNroInicialFactura.getText()));
            prefijoFactura.setFinfactura(Integer.parseInt(txtNroFinalFactura.getText()));
            prefijoFactura.setTipoDocumento(comboTipoDocumento.getSelectedItem().toString());
            prefijoFactura.setTimbrado(txtTimbrado.getText());
       
                try{
                    prefijoBD.insert(prefijoFactura); 
              
                    limpiar();
                }catch(Exception ex){
                    showMessageDialog(null, ex.getMessage(), "", ERROR_MESSAGE); 
                }  
            
        }
    }

    /*Borra los campos para ingresar otros nuevos */
    
    private void limpiar() {
        txtNroInicialFactura.setText("");
        txtPrefijo.setText("");
        txtTimbrado.setText("");
        txtNroFinalFactura.setText("");
        comboTipoDocumento.setSelectedIndex(-1);
    }
}
