/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;
import controlador.ProveedorControlador;
import controlador.ProyectoControlador;
import controlador.UsuarioControlador;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import modelo.Proveedor;
import modelo.Proyectos;
import modelo.Usuario;
/**
 *
 * @author Grossling
 */
public class ProyectosForm2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form componentesForm2
     */
    public ProyectosForm2() {
        initComponents();
    }
    
    Proyectos pry = new Proyectos();
    Proveedor pvdr = new Proveedor(); //solicitante
    Usuario usu = new Usuario();
    
    ProyectoControlador pryBD = new ProyectoControlador();
    ProveedorControlador pvdrBD = new ProveedorControlador();
    UsuarioControlador usuBD = new UsuarioControlador();
    
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modeloResponsables = new DefaultTableModel();
    DefaultTableModel modeloAdjudicaciones = new DefaultTableModel();
    DefaultTableModel modeloDevoluciones= new DefaultTableModel();
    DefaultTableModel modeloGastos= new DefaultTableModel();
    DefaultTableModel modeloFacturaciones= new DefaultTableModel();
    
    DefaultComboBoxModel modelComboSolicitante = new DefaultComboBoxModel();
    DefaultComboBoxModel modelComboJefe = new DefaultComboBoxModel();
    
    int k;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNuevo = new org.edisoncor.gui.button.ButtonTask();
        bCancelar = new org.edisoncor.gui.button.ButtonTask();
        bGuardar = new org.edisoncor.gui.button.ButtonTask();
        bFacturar = new org.edisoncor.gui.button.ButtonTask();
        bBuscar = new org.edisoncor.gui.button.ButtonTask();
        jPanel2 = new javax.swing.JPanel();
        bPrimero = new org.edisoncor.gui.button.ButtonTask();
        bAnterior = new org.edisoncor.gui.button.ButtonTask();
        bSiguiente = new org.edisoncor.gui.button.ButtonTask();
        bUltimo = new org.edisoncor.gui.button.ButtonTask();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboSolicitante = new javax.swing.JComboBox();
        jComboJefe = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableResponsables = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtfechaInicio = new javax.swing.JFormattedTextField();
        txtfechaFin = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUtilidad = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAdjudicacion = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDevolucion = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableDevolucion1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        bAnterior1 = new org.edisoncor.gui.button.ButtonTask();
        bSiguiente1 = new org.edisoncor.gui.button.ButtonTask();
        txtFechaFiltro = new datechooser.beans.DateChooserCombo();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableFacturaciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proyectos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proyecto.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N

        bNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430632277_document_add.png"))); // NOI18N
        bNuevo.setText("Nuevo");
        bNuevo.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bNuevo.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bNuevo.setDescription(" ");
        bNuevo.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bNuevo.setIconTextGap(2);
        bNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNuevoMouseClicked(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430630934_cross.png"))); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bCancelar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bCancelar.setDescription(" ");
        bCancelar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bCancelar.setIconTextGap(2);
        bCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarMouseClicked(evt);
            }
        });

        bGuardar.setForeground(new java.awt.Color(0, 51, 102));
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430629542_save_as-2-32.png"))); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bGuardar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bGuardar.setDescription(" ");
        bGuardar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bGuardar.setIconTextGap(2);
        bGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGuardarMouseClicked(evt);
            }
        });

        bFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430364091_my-invoices.png"))); // NOI18N
        bFacturar.setText("Facturar");
        bFacturar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bFacturar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bFacturar.setDescription(" ");
        bFacturar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bFacturar.setIconTextGap(2);
        bFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFacturarActionPerformed(evt);
            }
        });

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1430631782_search_32.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bBuscar.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bBuscar.setDescription(" ");
        bBuscar.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bBuscar.setIconTextGap(2);
        bBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(bFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N

        bPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431297857_go-first-32.png"))); // NOI18N
        bPrimero.setText("Primero");
        bPrimero.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bPrimero.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bPrimero.setDescription(" ");
        bPrimero.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bPrimero.setIconTextGap(2);
        bPrimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPrimeroMouseClicked(evt);
            }
        });

        bAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431298335_go-previous-32.png"))); // NOI18N
        bAnterior.setText("Anterior");
        bAnterior.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bAnterior.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bAnterior.setDescription(" ");
        bAnterior.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bAnterior.setIconTextGap(2);
        bAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAnteriorMouseClicked(evt);
            }
        });

        bSiguiente.setForeground(new java.awt.Color(0, 51, 102));
        bSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431298287_go-next-32.png"))); // NOI18N
        bSiguiente.setText("Siguiente");
        bSiguiente.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bSiguiente.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bSiguiente.setDescription(" ");
        bSiguiente.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bSiguiente.setIconTextGap(2);
        bSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSiguienteMouseClicked(evt);
            }
        });

        bUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431297875_go-last-32.png"))); // NOI18N
        bUltimo.setText("Ultimo");
        bUltimo.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bUltimo.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bUltimo.setDescription(" ");
        bUltimo.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bUltimo.setIconTextGap(2);
        bUltimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bUltimoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 94, 137));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 94, 137));
        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROYECTOS");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Proyecto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Aharoni", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setText("Código");

        txtCodigo.setName("txtcodigo"); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setName("txtdescripcion"); // NOI18N
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel5.setText("Estado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ABIERTO", "EN EJECUCION", "FINALIZADO", "CANCELADO" }));
        jComboBox1.setEnabled(false);

        jLabel7.setText("Solicitante");

        jLabel9.setText("Jefe");

        jTableResponsables.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableResponsables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableResponsables.setEnabled(false);
        jTableResponsables.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jTableResponsables);

        jLabel10.setText("Responsables");

        txtfechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        txtfechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel11.setText("Fecha inicio");

        jLabel12.setText("Fecha fin");

        txtPresupuesto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel14.setText("Presupuesto");

        jLabel17.setText("Utilidad(%)");

        txtUtilidad.setName("txtcodigo"); // NOI18N
        txtUtilidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUtilidadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboJefe, 0, 233, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jComboSolicitante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPresupuesto)
                            .addComponent(txtfechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfechaFin)
                            .addComponent(txtUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtfechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtfechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(txtUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(87, 123, 181));

        jLabel13.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ADJUDICACIONES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jTableAdjudicacion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableAdjudicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableAdjudicacion.setEnabled(false);
        jTableAdjudicacion.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTableAdjudicacion);

        jPanel6.setBackground(new java.awt.Color(87, 123, 181));

        jLabel15.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DEVOLUCIONES");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jTableDevolucion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDevolucion.setEnabled(false);
        jTableDevolucion.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(jTableDevolucion);

        jPanel7.setBackground(new java.awt.Color(87, 123, 181));

        jLabel16.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("GASTOS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jTableDevolucion1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableDevolucion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDevolucion1.setEnabled(false);
        jTableDevolucion1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jTableDevolucion1);

        jPanel9.setBackground(new java.awt.Color(87, 123, 181));

        jLabel18.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ACTIVIDADES");

        bAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431298335_go-previous-32.png"))); // NOI18N
        bAnterior1.setText(" ");
        bAnterior1.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bAnterior1.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bAnterior1.setDescription(" ");
        bAnterior1.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bAnterior1.setIconTextGap(2);
        bAnterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAnterior1MouseClicked(evt);
            }
        });
        bAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnterior1ActionPerformed(evt);
            }
        });

        bSiguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1431298287_go-next-32.png"))); // NOI18N
        bSiguiente1.setText(" ");
        bSiguiente1.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bSiguiente1.setCategorySmallFont(new java.awt.Font("Aharoni", 0, 5)); // NOI18N
        bSiguiente1.setDescription(" ");
        bSiguiente1.setFont(new java.awt.Font("Algerian", 0, 5)); // NOI18N
        bSiguiente1.setIconTextGap(2);
        bSiguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSiguiente1MouseClicked(evt);
            }
        });
        bSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguiente1ActionPerformed(evt);
            }
        });

        txtFechaFiltro.setFormat(2);
        try {
            txtFechaFiltro.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }
        txtFechaFiltro.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                txtFechaFiltroOnCommit(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(bSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFechaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(87, 123, 181));

        jLabel19.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("FACTURACIONES");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jTableFacturaciones.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableFacturaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFacturaciones.setEnabled(false);
        jTableFacturaciones.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(jTableFacturaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGuardarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bGuardar.isEnabled() == false){
            return;
        } else {
            guardar();
        }
    }//GEN-LAST:event_bGuardarMouseClicked

    private void bNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNuevoMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bNuevo.isEnabled() == false){
            return;
        } else {
            nuevo();
        }
    }//GEN-LAST:event_bNuevoMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        getProyectos();
        getSolicitantes();
        getJefes();
        nuevo();
    }//GEN-LAST:event_formInternalFrameOpened

    private void bCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bCancelar.isEnabled() == false){
            return;
        } else {
            cancelar();
        }
    }//GEN-LAST:event_bCancelarMouseClicked

    private void bPrimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPrimeroMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bPrimero.isEnabled() == false){
            return;
        } else {
            primero();
        }
    }//GEN-LAST:event_bPrimeroMouseClicked

    private void bUltimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUltimoMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bUltimo.isEnabled() == false){
            return;
        } else {
            ultimo();
        }
    }//GEN-LAST:event_bUltimoMouseClicked

    private void bAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnteriorMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bAnterior.isEnabled() == false){
            return;
        } else {
            anterior();
        }
    }//GEN-LAST:event_bAnteriorMouseClicked

    private void bSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSiguienteMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bSiguiente.isEnabled() == false){
            return;
        } else {
            siguiente();
        }
    }//GEN-LAST:event_bSiguienteMouseClicked

    private void bBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscarMouseClicked
        if (evt.isMetaDown()){
            return;
        } else if (bBuscar.isEnabled() == false){
            return;
        } else {
            buscar();
        }
    }//GEN-LAST:event_bBuscarMouseClicked

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (txtDescripcion.isEnabled() == true){
            return;
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("*".equals(txtCodigo.getText())) {

                BuscarForm bf = new BuscarForm(null, true);
                bf.columnas = "codigo, descripcion, fecha_ini, fecha_fin, estado";
                bf.tabla = "Proyectos";
                bf.order = "id";
                bf.filtroBusqueda = "";
                bf.setLocationRelativeTo(this);
                bf.setVisible(true);

                for(int c=0; c<modelo.getRowCount(); c ++){
                    if (modelo.getValueAt(c, 1).toString().equals(bf.retorno)){
                        modoBusqueda(false);
                        establecerBotones("Edicion");
                        k = c;
                        datosActuales();
                        return;
                    }
                }

            }

            for(int c=0; c<modelo.getRowCount(); c ++){
                if (modelo.getValueAt(c, 1).toString().equals(txtCodigo.getText())){
                    modoBusqueda(false);
                    establecerBotones("Edicion");
                    k = c;
                    datosActuales();
                    return;
                }
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtUtilidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtilidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUtilidadKeyPressed

    private void bAnterior1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnterior1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAnterior1MouseClicked

    private void bSiguiente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSiguiente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSiguiente1MouseClicked

    private void bSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguiente1ActionPerformed
        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = formato.parse(txtFechaFiltro.getText());
            Date fechaIni = formato.parse(txtfechaInicio.getText());
            Date fechaFin = formato.parse(txtfechaFin.getText());
            
            Calendar cal = Calendar.getInstance();
            Calendar calIni = Calendar.getInstance();
            Calendar calFin = Calendar.getInstance();
            
            cal.setTime(fecha);
            calIni.setTime(fechaIni);
            calFin.setTime(fechaFin);
            
            if (cal.equals(calFin)){
                return;
            }
            
            cal.add(Calendar.DATE, 1);
            
            txtFechaFiltro.setSelectedDate(cal);
            datosActuales();
        } catch (ParseException ex) {
            
        }     
    }//GEN-LAST:event_bSiguiente1ActionPerformed

    private void bAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnterior1ActionPerformed
        try {
             SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = formato.parse(txtFechaFiltro.getText());
            Date fechaIni = formato.parse(txtfechaInicio.getText());
            Date fechaFin = formato.parse(txtfechaFin.getText());
            
            Calendar cal = Calendar.getInstance();
            Calendar calIni = Calendar.getInstance();
            Calendar calFin = Calendar.getInstance();
            
            cal.setTime(fecha);
            calIni.setTime(fechaIni);
            calFin.setTime(fechaFin);
            
            if (cal.equals(calIni)){
                return;
            }
            
            cal.add(Calendar.DATE, -1);
            
            txtFechaFiltro.setSelectedDate(cal);
            datosActuales();
        } catch (ParseException ex) {
            
        }          
    }//GEN-LAST:event_bAnterior1ActionPerformed

    private void txtFechaFiltroOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_txtFechaFiltroOnCommit
        datosActuales();
    }//GEN-LAST:event_txtFechaFiltroOnCommit

    private void bFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFacturarActionPerformed
        try {
            ProyectoControlador pryCont = new ProyectoControlador();
            pryCont.guardarProyectoAFacturar(txtCodigo.getText(), pryCont.calcularPrecioAFacturar(txtCodigo.getText()));
            facturaProyecto prueba = new facturaProyecto();
            prueba.setVisible(true);
            
        } catch (Exception ex) {
            Logger.getLogger(ProyectosForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bFacturarActionPerformed

    private void datosActuales(){
            try {
                txtCodigo.setText(modelo.getValueAt(k, 1).toString());
                txtDescripcion.setText(modelo.getValueAt(k, 8).toString());
                jComboBox1.setSelectedIndex((int) modelo.getValueAt(k, 6));
                txtPresupuesto.setValue(modelo.getValueAt(k, 7)); 
                SimpleDateFormat formatoRecibido = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat formatoFinal = new SimpleDateFormat("dd/MM/yyyy");
                Date fecha1 = formatoRecibido.parse(modelo.getValueAt(k, 4).toString());
                Date fecha2 = formatoRecibido.parse(modelo.getValueAt(k, 5).toString());
                txtfechaInicio.setText(formatoFinal.format(fecha1));
                txtfechaFin.setText(formatoFinal.format(fecha2));
                getAdjudicaciones((String) modelo.getValueAt(k, 1), txtFechaFiltro.getText());
                getDevoluciones((String) modelo.getValueAt(k, 1), txtFechaFiltro.getText());
                getGastos((String) modelo.getValueAt(k, 1), txtFechaFiltro.getText());
                getFacturaciones((String) modelo.getValueAt(k, 1), txtFechaFiltro.getText());
                txtUtilidad.setText(modelo.getValueAt(k, 9).toString());
                try {
                    jComboSolicitante.setSelectedItem(pvdrBD.getDato((Integer) modelo.getValueAt(k, 2)));
                    jComboJefe.setSelectedItem(usuBD.getDatoUsuario((Integer) modelo.getValueAt(k, 3)));
                } catch (Exception ex) {
                    //showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
                }
            } catch (ParseException ex) {
                Logger.getLogger(ProyectosForm2.class.getName()).log(Level.SEVERE,null,ex); 
            }
    }
    
    private void primero(){
        if (modelo.getRowCount() == 0) {
            showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
            return;
        }    
            k = 0;
            datosActuales();
    }
    
    private void ultimo(){
         if (modelo.getRowCount() == 0) {
             showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
             return;
         }  
            k = modelo.getRowCount() - 1;
            datosActuales();
            
     }
    
    private void anterior(){
        if (modelo.getRowCount() == 0) {
             showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
             return;
         }      
            k = k - 1;
            if (k < 0) {
                showMessageDialog(null, "Has llegado al primer registro.", "Atención", INFORMATION_MESSAGE);
                k = k + 1;
                return;
            }
            datosActuales();
    }
    
    private void siguiente(){
        if (modelo.getRowCount() == 0) {
             showMessageDialog(null, "No hay registros.", "Atención", INFORMATION_MESSAGE); 
             return;
         }  
            k = k + 1;
            if (k == modelo.getRowCount()) {
                showMessageDialog(null, "Has llegado al ultimo registro.", "Atención", INFORMATION_MESSAGE);
                k = k - 1;
                return;
            }
            datosActuales();
    }
    
    private void buscar(){
        limpiar();
        establecerBotones("Buscar");
        modoBusqueda(true);
    }
    
    private void modoBusqueda(boolean v){
        if (v == true) {
        txtCodigo.requestFocusInWindow();
        txtCodigo.setBackground(Color.yellow);
        txtDescripcion.setEnabled(false);
        txtfechaInicio.setEnabled(false);
        txtfechaFin.setEnabled(false);
        txtUtilidad.setEnabled(false);
        txtPresupuesto.setEnabled(false);
        jComboBox1.setEnabled(false);
        jComboSolicitante.setEnabled(false);
        jComboJefe.setEnabled(false);
        } else {
        txtCodigo.setBackground(Color.white);
        txtDescripcion.setEnabled(true);
        txtfechaInicio.setEnabled(true);
        txtfechaFin.setEnabled(true);
        txtPresupuesto.setEnabled(true);
        txtUtilidad.setEnabled(true);
        jComboBox1.setEnabled(false);
        jComboSolicitante.setEnabled(true);
        jComboJefe.setEnabled(true);
        }
    }
    
    @SuppressWarnings("UnnecessaryReturnStatement")
    private void guardar(){
        if ("".equals(txtCodigo.getText())) {
            showMessageDialog(null, "Debe ingresar un código.", "Atención", INFORMATION_MESSAGE);
            txtCodigo.requestFocusInWindow();
            return;
        } else if ("".equals(txtfechaInicio.getText())) {
            showMessageDialog(null, "Debe ingresar la fecha de inicio.", "Atención", INFORMATION_MESSAGE);
            txtfechaInicio.requestFocusInWindow();
            return;
        } else if ("".equals(txtfechaFin.getText())) {
            showMessageDialog(null, "Debe ingresar la fecha de finalizacion", "Atención", INFORMATION_MESSAGE);
            txtfechaFin.requestFocusInWindow();
            return;
        } else if ("".equals(txtDescripcion.getText())) {
            showMessageDialog(null, "Debe ingresar la descripción.", "Atención", INFORMATION_MESSAGE);
            txtDescripcion.requestFocusInWindow();
            return;
        } else if (("".equals(txtPresupuesto.getText())) || ("0".equals(txtPresupuesto.getText())) ) {
            showMessageDialog(null, "Debe ingresar el presupuesto.", "Atención", INFORMATION_MESSAGE);
            txtPresupuesto.requestFocusInWindow();
            return;
        } else if (("".equals(txtUtilidad.getText())) || ("0".equals(txtUtilidad.getText())) ) {
            showMessageDialog(null, "Debe ingresar la utilidad.", "Atención", INFORMATION_MESSAGE);
            txtUtilidad.requestFocusInWindow();
            return;
        } 
        else {
            try {
                pry.setCodigo(txtCodigo.getText());
                
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date fecha1 = formato.parse(txtfechaInicio.getText());
                Date fecha2 = formato.parse(txtfechaFin.getText());
                
                pry.setFechaIni(fecha1);
                pry.setFechaFin(fecha2);
                pry.setDescripcion(txtDescripcion.getText());
                pry.setSolicitante(pvdrBD.getCodigo((String) jComboSolicitante.getSelectedItem()));
                pry.setJefe(usuBD.getIdUsuario((String) jComboJefe.getSelectedItem()));
                pry.setEstado(jComboBox1.getSelectedIndex());
                pry.setUtilidad(Integer.parseInt(txtUtilidad.getText()));
                pry.setPresupuesto(Integer.parseInt(txtPresupuesto.getValue().toString()));
                
                if (bNuevo.isEnabled() == false) {
                    try {
                        pryBD.insert(pry);
                        nuevo();
                        getProyectos();
                    } catch (Exception ex) {
                        showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
                    }
                } else {
                    try {
                        pry.setId((Integer) modelo.getValueAt(k, 0));
                        pryBD.update(pry);
                        getProyectos();
                        datosActuales();
                    } catch (Exception ex) {
                        showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(ProyectosForm2.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }
    
    private void cancelar(){
        if(showConfirmDialog (null, "Está seguro de cancelar la operación?", "Confirmar", YES_NO_OPTION) == YES_OPTION){
            getProyectos();
            if (modelo.getRowCount() == 0) {
                limpiar(); 
                establecerBotones("Vacio"); 
                modoBusqueda(false); 
                return;
            }
            if (k >= 0){
                    limpiar(); 
                    datosActuales(); 
                    establecerBotones("Edicion");
                    modoBusqueda(false);
                    return;
            }
        }
    }
    
    private void nuevo() {
        limpiar();
        establecerBotones("Nuevo");
        try {
            jComboBox1.setSelectedIndex(0);
            txtCodigo.requestFocusInWindow();
        } catch (Exception ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void limpiar() {
        txtCodigo.setText("");
        txtfechaInicio.setText("");
        txtfechaFin.setText("");
        txtDescripcion.setText("");
        txtPresupuesto.setText("");
        txtUtilidad.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboSolicitante.setSelectedIndex(0);
        jComboJefe.setSelectedIndex(0);
        txtFechaFiltro.setText("");
        getDevoluciones("","12/12/2200");
        getAdjudicaciones("","12/12/2200");
        getGastos("","12/12/2200");
        getFacturaciones("","12/12/2200");
    }
    
    private void getProyectos() {
        try {
            try (ResultSet rs = pryBD.datos()) {
                
                modelo.setRowCount(0);
                modelo.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs.getMetaData();
                
                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modelo.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void getSolicitantes() {
        try {
            try (ResultSet rs = pvdrBD.datoCombo()) {
                
                modelComboSolicitante.removeAllElements();
                
                while (rs.next()) {
                    modelComboSolicitante.addElement(rs.getObject("dato").toString());
                }
            jComboSolicitante.setModel(modelComboSolicitante);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void getJefes() {
        try {
            try (ResultSet rs = usuBD.datoCombo()) {
                
                modelComboJefe.removeAllElements();
                
                while (rs.next()) {
                    modelComboJefe.addElement(rs.getObject("dato").toString());
                }
            jComboJefe.setModel(modelComboJefe);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void getAdjudicaciones(String codProyecto, String fecha) {
        try {
            try (ResultSet rs1 = pryBD.datosAdjudicaciones(codProyecto, fecha)) {
                
                modeloAdjudicaciones.setRowCount(0);
                modeloAdjudicaciones.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs1.getMetaData();

                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modeloAdjudicaciones.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs1.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs1.getObject(i+1);
                    }
                    modeloAdjudicaciones.addRow(fila);
                }
                jTableAdjudicacion.setModel(modeloAdjudicaciones);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
     private void getDevoluciones(String codProyecto, String fecha) {
        try {
            try (ResultSet rs1 = pryBD.datosDevoluciones(codProyecto, fecha)) {
                
                modeloDevoluciones.setRowCount(0);
                modeloDevoluciones.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs1.getMetaData();

                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modeloDevoluciones.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs1.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs1.getObject(i+1);
                    }
                    modeloDevoluciones.addRow(fila);
                }
                jTableDevolucion.setModel(modeloDevoluciones);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
     
     private void getGastos(String codProyecto, String fecha) {
        try {
            try (ResultSet rs1 = pryBD.datosGastos(codProyecto, fecha)) {
                
                modeloGastos.setRowCount(0);
                modeloGastos.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs1.getMetaData();

                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modeloGastos.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs1.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs1.getObject(i+1);
                    }
                    modeloGastos.addRow(fila);
                }
                jTableDevolucion1.setModel(modeloGastos);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
     
     private void getFacturaciones(String codProyecto, String fecha) {
        try {
            try (ResultSet rs1 = pryBD.datosFacturaciones(codProyecto, fecha)) {
                
                modeloFacturaciones.setRowCount(0);
                modeloFacturaciones.setColumnCount(0);
                
                ResultSetMetaData rsMd = rs1.getMetaData();

                int cantidadColumnas = rsMd.getColumnCount();
                
                for (int i = 1; i <= cantidadColumnas; i++) {
                    modeloFacturaciones.addColumn(rsMd.getColumnLabel(i));
                }

                while (rs1.next()) {
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        fila[i]=rs1.getObject(i+1);
                    }
                    modeloFacturaciones.addRow(fila);
                }
                jTableFacturaciones.setModel(modeloFacturaciones);
            } catch (Exception ex) {
                showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
            }
        } catch (HeadlessException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private void establecerBotones(String modo) {
        switch (modo) {
            case "Nuevo":
                bNuevo.setEnabled(false);
                bFacturar.setEnabled(false);
                bCancelar.setEnabled(true);
                bGuardar.setEnabled(true);
                bAnterior.setEnabled(false);
                bSiguiente.setEnabled(false);
                bPrimero.setEnabled(false);
                bUltimo.setEnabled(false);
                bBuscar.setEnabled(false);
                break;
            case "Edicion":
                bNuevo.setEnabled(true);
                bFacturar.setEnabled(true);
                bCancelar.setEnabled(false);
                bGuardar.setEnabled(true);
                bAnterior.setEnabled(true);
                bSiguiente.setEnabled(true);
                bPrimero.setEnabled(true);
                bUltimo.setEnabled(true);
                bBuscar.setEnabled(true);
                break;
            case "Vacio":
                bNuevo.setEnabled(true);
                bFacturar.setEnabled(false);
                bCancelar.setEnabled(false);
                bGuardar.setEnabled(false);
                bAnterior.setEnabled(false);
                bSiguiente.setEnabled(false);
                bPrimero.setEnabled(false);
                bUltimo.setEnabled(false);
                bBuscar.setEnabled(false);
                break;
            case "Buscar":
                bNuevo.setEnabled(false);
                bFacturar.setEnabled(false);
                bCancelar.setEnabled(true);
                bGuardar.setEnabled(false);
                bAnterior.setEnabled(false);
                bSiguiente.setEnabled(false);
                bPrimero.setEnabled(false);
                bUltimo.setEnabled(false);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask bAnterior;
    private org.edisoncor.gui.button.ButtonTask bAnterior1;
    private org.edisoncor.gui.button.ButtonTask bBuscar;
    private org.edisoncor.gui.button.ButtonTask bCancelar;
    private org.edisoncor.gui.button.ButtonTask bFacturar;
    private org.edisoncor.gui.button.ButtonTask bGuardar;
    private org.edisoncor.gui.button.ButtonTask bNuevo;
    private org.edisoncor.gui.button.ButtonTask bPrimero;
    private org.edisoncor.gui.button.ButtonTask bSiguiente;
    private org.edisoncor.gui.button.ButtonTask bSiguiente1;
    private org.edisoncor.gui.button.ButtonTask bUltimo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboJefe;
    private javax.swing.JComboBox jComboSolicitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableAdjudicacion;
    private javax.swing.JTable jTableDevolucion;
    private javax.swing.JTable jTableDevolucion1;
    private javax.swing.JTable jTableFacturaciones;
    private javax.swing.JTable jTableResponsables;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private datechooser.beans.DateChooserCombo txtFechaFiltro;
    private javax.swing.JFormattedTextField txtPresupuesto;
    private javax.swing.JTextField txtUtilidad;
    private javax.swing.JFormattedTextField txtfechaFin;
    private javax.swing.JFormattedTextField txtfechaInicio;
    // End of variables declaration//GEN-END:variables
}

