package modelo;
// Generated 15-jul-2015 17:18:17 by Hibernate Tools 3.6.0



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int clienteId;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String estado;
     private String dv;
     private String codigocliente;
     private Integer limitecredito;
     private String tipocliente;
     private String cedula;

    public Cliente() {
    }

	
    public Cliente(int clienteId, String nombre, String estado) {
        this.clienteId = clienteId;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Cliente(int clienteId, String nombre, String apellido, String direccion, String telefono, String estado, String dv, String codigocliente, Integer limitecredito, String tipocliente, String cedula) {
       this.clienteId = clienteId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estado = estado;
       this.dv = dv;
       this.codigocliente = codigocliente;
       this.limitecredito = limitecredito;
       this.tipocliente = tipocliente;
       this.cedula = cedula;
    }
   
    public int getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDv() {
        return this.dv;
    }
    
    public void setDv(String dv) {
        this.dv = dv;
    }
    public String getCodigocliente() {
        return this.codigocliente;
    }
    
    public void setCodigocliente(String codigocliente) {
        this.codigocliente = codigocliente;
    }
    public Integer getLimitecredito() {
        return this.limitecredito;
    }
    
    public void setLimitecredito(Integer limitecredito) {
        this.limitecredito = limitecredito;
    }
    public String getTipocliente() {
        return this.tipocliente;
    }
    
    public void setTipocliente(String tipocliente) {
        this.tipocliente = tipocliente;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }




}


