package modelo;
// Generated 15-jul-2015 17:18:17 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int compraId;
     private int nroFactura;
     private Date fecha;
     private Integer proyectoId;
     private int precioTotal;
     private int cantidadTotal;
     private Integer descuento;
     private Integer iva;
     private String pagoContado;
     private String estado;
     private Integer factReferenciada;
     private char esFactura;
     private int proveedorId;
     private Date vencimiento;
     private String codDeposito;
     private Date fechaRecepcion;
     private Integer pagoEn;
     private Integer monedaId;
     private String nroPrefijo;

    public Compra() {
    }

	
    public Compra(int compraId, int nroFactura, Date fecha, int precioTotal, int cantidadTotal, String pagoContado, String estado, char esFactura, int proveedorId, Date vencimiento) {
        this.compraId = compraId;
        this.nroFactura = nroFactura;
        this.fecha = fecha;
        this.precioTotal = precioTotal;
        this.cantidadTotal = cantidadTotal;
        this.pagoContado = pagoContado;
        this.estado = estado;
        this.esFactura = esFactura;
        this.proveedorId = proveedorId;
        this.vencimiento = vencimiento;
    }
    public Compra(int compraId, int nroFactura, Date fecha, Integer proyectoId, int precioTotal, int cantidadTotal, Integer descuento, Integer iva, String pagoContado, String estado, Integer factReferenciada, char esFactura, int proveedorId, Date vencimiento, String codDeposito, Date fechaRecepcion, Integer pagoEn, Integer monedaId, String nroPrefijo) {
       this.compraId = compraId;
       this.nroFactura = nroFactura;
       this.fecha = fecha;
       this.proyectoId = proyectoId;
       this.precioTotal = precioTotal;
       this.cantidadTotal = cantidadTotal;
       this.descuento = descuento;
       this.iva = iva;
       this.pagoContado = pagoContado;
       this.estado = estado;
       this.factReferenciada = factReferenciada;
       this.esFactura = esFactura;
       this.proveedorId = proveedorId;
       this.vencimiento = vencimiento;
       this.codDeposito = codDeposito;
       this.fechaRecepcion = fechaRecepcion;
       this.pagoEn = pagoEn;
       this.monedaId = monedaId;
       this.nroPrefijo = nroPrefijo;
    }
   
    public int getCompraId() {
        return this.compraId;
    }
    
    public void setCompraId(int compraId) {
        this.compraId = compraId;
    }
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(Integer proyectoId) {
        this.proyectoId = proyectoId;
    }
    public int getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(int precioTotal) {
        this.precioTotal = precioTotal;
    }
    public int getCantidadTotal() {
        return this.cantidadTotal;
    }
    
    public void setCantidadTotal(int cantidadTotal) {
        this.cantidadTotal = cantidadTotal;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }
    public Integer getIva() {
        return this.iva;
    }
    
    public void setIva(Integer iva) {
        this.iva = iva;
    }
    public String getPagoContado() {
        return this.pagoContado;
    }
    
    public void setPagoContado(String pagoContado) {
        this.pagoContado = pagoContado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getFactReferenciada() {
        return this.factReferenciada;
    }
    
    public void setFactReferenciada(Integer factReferenciada) {
        this.factReferenciada = factReferenciada;
    }
    public char getEsFactura() {
        return this.esFactura;
    }
    
    public void setEsFactura(char esFactura) {
        this.esFactura = esFactura;
    }
    public int getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(int proveedorId) {
        this.proveedorId = proveedorId;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public String getCodDeposito() {
        return this.codDeposito;
    }
    
    public void setCodDeposito(String codDeposito) {
        this.codDeposito = codDeposito;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Integer getPagoEn() {
        return this.pagoEn;
    }
    
    public void setPagoEn(Integer pagoEn) {
        this.pagoEn = pagoEn;
    }
    public Integer getMonedaId() {
        return this.monedaId;
    }
    
    public void setMonedaId(Integer monedaId) {
        this.monedaId = monedaId;
    }
    public String getNroPrefijo() {
        return this.nroPrefijo;
    }
    
    public void setNroPrefijo(String nroPrefijo) {
        this.nroPrefijo = nroPrefijo;
    }




}


