package modelo;
// Generated 08-ago-2015 20:27:41 by Hibernate Tools 3.6.0



/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String descripcion;

    public Deposito() {
    }

	
    public Deposito(String codigo) {
        this.codigo = codigo;
    }
    public Deposito(String codigo, String nombre, String descripcion) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String toString(){
        return this.nombre;
    }

}


