package modelo;
// Generated 15-jul-2015 17:18:17 by Hibernate Tools 3.6.0



/**
 * DetalleRemision generated by hbm2java
 */
public class DetalleRemision  implements java.io.Serializable {


     private int detalleRemisionId;
     private int componenteId;
     private int cantidad;
     private String codigoComponente;
     private String descripcion;
     private int remisionId;

    public DetalleRemision() {
    }

	
    public DetalleRemision(int detalleRemisionId, int componenteId, int cantidad, String codigoComponente, int remisionId) {
        this.detalleRemisionId = detalleRemisionId;
        this.componenteId = componenteId;
        this.cantidad = cantidad;
        this.codigoComponente = codigoComponente;
        this.remisionId = remisionId;
    }
    public DetalleRemision(int detalleRemisionId, int componenteId, int cantidad, String codigoComponente, String descripcion, int remisionId) {
       this.detalleRemisionId = detalleRemisionId;
       this.componenteId = componenteId;
       this.cantidad = cantidad;
       this.codigoComponente = codigoComponente;
       this.descripcion = descripcion;
       this.remisionId = remisionId;
    }
   
    public int getDetalleRemisionId() {
        return this.detalleRemisionId;
    }
    
    public void setDetalleRemisionId(int detalleRemisionId) {
        this.detalleRemisionId = detalleRemisionId;
    }
    public int getComponenteId() {
        return this.componenteId;
    }
    
    public void setComponenteId(int componenteId) {
        this.componenteId = componenteId;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getCodigoComponente() {
        return this.codigoComponente;
    }
    
    public void setCodigoComponente(String codigoComponente) {
        this.codigoComponente = codigoComponente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getRemisionId() {
        return this.remisionId;
    }
    
    public void setRemisionId(int remisionId) {
        this.remisionId = remisionId;
    }




}


