package modelo;
// Generated Dec 21, 2015 6:00:36 PM by Hibernate Tools 3.6.0



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private int detalleFacturaId;
     private int cantidad;
     private int subTotal;
     private String descripcion;
     private int ventaId;
     private String codigo;
     private Integer precioUnitario;
     private Integer exentas;

    public DetalleVenta() {
    }

	
    public DetalleVenta(int detalleFacturaId, int cantidad, int subTotal, int ventaId) {
        this.detalleFacturaId = detalleFacturaId;
        this.cantidad = cantidad;
        this.subTotal = subTotal;
        this.ventaId = ventaId;
    }
    public DetalleVenta(int detalleFacturaId, int cantidad, int subTotal, String descripcion, int ventaId, String codigo, Integer precioUnitario, Integer exentas) {
       this.detalleFacturaId = detalleFacturaId;
       this.cantidad = cantidad;
       this.subTotal = subTotal;
       this.descripcion = descripcion;
       this.ventaId = ventaId;
       this.codigo = codigo;
       this.precioUnitario = precioUnitario;
       this.exentas = exentas;
    }
   
    public int getDetalleFacturaId() {
        return this.detalleFacturaId;
    }
    
    public void setDetalleFacturaId(int detalleFacturaId) {
        this.detalleFacturaId = detalleFacturaId;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(int subTotal) {
        this.subTotal = subTotal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(int ventaId) {
        this.ventaId = ventaId;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Integer getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Integer precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Integer getExentas() {
        return this.exentas;
    }
    
    public void setExentas(Integer exentas) {
        this.exentas = exentas;
    }




}


