package modelo;
// Generated Jun 27, 2015 5:39:32 PM by Hibernate Tools 3.6.0



/**
 * Moneda generated by hbm2java
 */
public class Moneda  implements java.io.Serializable {


     private int monedaId;
     private String nombre;

    public Moneda() {
    }

	
    public Moneda(int monedaId) {
        this.monedaId = monedaId;
    }
    public Moneda(int monedaId, String nombre) {
       this.monedaId = monedaId;
       this.nombre = nombre;
    }
   
    public int getMonedaId() {
        return this.monedaId;
    }
    
    public void setMonedaId(int monedaId) {
        this.monedaId = monedaId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public String toString() {
        return this.nombre;
    }




}


