package modelo;
// Generated 08-ago-2015 20:27:41 by Hibernate Tools 3.6.0



/**
 * PrefijoFactura generated by hbm2java
 */
public class PrefijoFactura  implements java.io.Serializable {


     private int idprefijo;
     private String prefijo;
     private Integer principiofactura;
     private Integer finfactura;
     private String tipoDocumento;

    public PrefijoFactura() {
    }

	
    public PrefijoFactura(int idprefijo, String tipoDocumento) {
        this.idprefijo = idprefijo;
        this.tipoDocumento = tipoDocumento;
    }
    public PrefijoFactura(int idprefijo, String prefijo, Integer principiofactura, Integer finfactura, String tipoDocumento) {
       this.idprefijo = idprefijo;
       this.prefijo = prefijo;
       this.principiofactura = principiofactura;
       this.finfactura = finfactura;
       this.tipoDocumento = tipoDocumento;
    }
   
    public int getIdprefijo() {
        return this.idprefijo;
    }
    
    public void setIdprefijo(int idprefijo) {
        this.idprefijo = idprefijo;
    }
    public String getPrefijo() {
        return this.prefijo;
    }
    
    public void setPrefijo(String prefijo) {
        this.prefijo = prefijo;
    }
    public Integer getPrincipiofactura() {
        return this.principiofactura;
    }
    
    public void setPrincipiofactura(Integer principiofactura) {
        this.principiofactura = principiofactura;
    }
    public Integer getFinfactura() {
        return this.finfactura;
    }
    
    public void setFinfactura(Integer finfactura) {
        this.finfactura = finfactura;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }




}


