package modelo;
// Generated 15-jul-2015 17:18:17 by Hibernate Tools 3.6.0



/**
 * ResponsablesProyecto generated by hbm2java
 */
public class ResponsablesProyecto  implements java.io.Serializable {


     private int id;
     private Integer idProyecto;
     private Integer idUsuario;

    public ResponsablesProyecto() {
    }

	
    public ResponsablesProyecto(int id) {
        this.id = id;
    }
    public ResponsablesProyecto(int id, Integer idProyecto, Integer idUsuario) {
       this.id = id;
       this.idProyecto = idProyecto;
       this.idUsuario = idUsuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }




}


