package modelo;
// Generated Jun 27, 2015 5:39:32 PM by Hibernate Tools 3.6.0



/**
 * RolVentanas generated by hbm2java
 */
public class RolVentanas  implements java.io.Serializable {


     private int idRolVentana;
     private Integer rolId;
     private Integer idVentana;

    public RolVentanas() {
    }

	
    public RolVentanas(int idRolVentana) {
        this.idRolVentana = idRolVentana;
    }
    public RolVentanas(int idRolVentana, Integer rolId, Integer idVentana) {
       this.idRolVentana = idRolVentana;
       this.rolId = rolId;
       this.idVentana = idVentana;
    }
   
    public int getIdRolVentana() {
        return this.idRolVentana;
    }
    
    public void setIdRolVentana(int idRolVentana) {
        this.idRolVentana = idRolVentana;
    }
    public Integer getRolId() {
        return this.rolId;
    }
    
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }
    public Integer getIdVentana() {
        return this.idVentana;
    }
    
    public void setIdVentana(Integer idVentana) {
        this.idVentana = idVentana;
    }




}


