package modelo;
// Generated 08-ago-2015 20:27:41 by Hibernate Tools 3.6.0



/**
 * SaldoVenta generated by hbm2java
 */
public class SaldoVenta  implements java.io.Serializable {


     private int saldoVentaId;
     private Integer prefijo;
     private Integer numero;
     private Integer saldo;
     private String estado;
     private String esFactura;

    public SaldoVenta() {
    }

	
    public SaldoVenta(int saldoVentaId) {
        this.saldoVentaId = saldoVentaId;
    }
    public SaldoVenta(int saldoVentaId, Integer prefijo, Integer numero, Integer saldo, String estado, String esFactura) {
       this.saldoVentaId = saldoVentaId;
       this.prefijo = prefijo;
       this.numero = numero;
       this.saldo = saldo;
       this.estado = estado;
       this.esFactura = esFactura;
    }
   
    public int getSaldoVentaId() {
        return this.saldoVentaId;
    }
    
    public void setSaldoVentaId(int saldoVentaId) {
        this.saldoVentaId = saldoVentaId;
    }
    public Integer getPrefijo() {
        return this.prefijo;
    }
    
    public void setPrefijo(Integer prefijo) {
        this.prefijo = prefijo;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getEsFactura() {
        return this.esFactura;
    }
    
    public void setEsFactura(String esFactura) {
        this.esFactura = esFactura;
    }




}


