package modelo;
// Generated 08-ago-2015 20:27:41 by Hibernate Tools 3.6.0



/**
 * SaldoPersona generated by hbm2java
 */
public class SaldoPersona  implements java.io.Serializable {


     private int saldoPersonaId;
     private Integer saldo;
     private String estado;
     private Integer proveedorId;
     private Integer clienteId;

    public SaldoPersona() {
    }

	
    public SaldoPersona(int saldoPersonaId) {
        this.saldoPersonaId = saldoPersonaId;
    }
    public SaldoPersona(int saldoPersonaId, Integer saldo, String estado, Integer proveedorId, Integer clienteId) {
       this.saldoPersonaId = saldoPersonaId;
       this.saldo = saldo;
       this.estado = estado;
       this.proveedorId = proveedorId;
       this.clienteId = clienteId;
    }
   
    public int getSaldoPersonaId() {
        return this.saldoPersonaId;
    }
    
    public void setSaldoPersonaId(int saldoPersonaId) {
        this.saldoPersonaId = saldoPersonaId;
    }
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(Integer proveedorId) {
        this.proveedorId = proveedorId;
    }
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }




}


