package modelo;
// Generated 08-ago-2015 20:27:41 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private int codigoInterno;
     private Integer numero;
     private Date fechaIngreso;
     private String comentarios;
     private Integer ajuste;
     private String deposito;
     private String proyecto;

    public Salida() {
    }

	
    public Salida(int codigoInterno) {
        this.codigoInterno = codigoInterno;
    }
    public Salida(int codigoInterno, Integer numero, Date fechaIngreso, String comentarios, Integer ajuste, String deposito, String proyecto) {
       this.codigoInterno = codigoInterno;
       this.numero = numero;
       this.fechaIngreso = fechaIngreso;
       this.comentarios = comentarios;
       this.ajuste = ajuste;
       this.deposito = deposito;
       this.proyecto = proyecto;
    }
   
    public int getCodigoInterno() {
        return this.codigoInterno;
    }
    
    public void setCodigoInterno(int codigoInterno) {
        this.codigoInterno = codigoInterno;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Integer getAjuste() {
        return this.ajuste;
    }
    
    public void setAjuste(Integer ajuste) {
        this.ajuste = ajuste;
    }
    public String getDeposito() {
        return this.deposito;
    }
    
    public void setDeposito(String deposito) {
        this.deposito = deposito;
    }
    public String getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }




}


