package modelo;
// Generated Dec 8, 2015 5:15:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Transferencia generated by hbm2java
 */
public class Transferencia  implements java.io.Serializable {


     private int codigoInterno;
     private Integer numero;
     private Date fechaTransferencia;
     private String comentarios;
     private String origen;
     private String destino;

    public Transferencia() {
    }

	
    public Transferencia(int codigoInterno) {
        this.codigoInterno = codigoInterno;
    }
    public Transferencia(int codigoInterno, Integer numero, Date fechaTransferencia, String comentarios, String origen, String destino) {
       this.codigoInterno = codigoInterno;
       this.numero = numero;
       this.fechaTransferencia = fechaTransferencia;
       this.comentarios = comentarios;
       this.origen = origen;
       this.destino = destino;
    }
   
    public int getCodigoInterno() {
        return this.codigoInterno;
    }
    
    public void setCodigoInterno(int codigoInterno) {
        this.codigoInterno = codigoInterno;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Date getFechaTransferencia() {
        return this.fechaTransferencia;
    }
    
    public void setFechaTransferencia(Date fechaTransferencia) {
        this.fechaTransferencia = fechaTransferencia;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }




}


